airQbank = [
{ "question": "(Refer to Figure) You have been asked to inspect the tower just north of Binford. What restrictions should the Remote PIC be concerned about when operating the sUAS?  ", 
  "figure": "figure26.png",
  "answers": [ "None. The tower is in Class G airspace up to 1200 AGL.", 
               "Restricted airspace exists around the tower. Thus permissions are required from the controlling agency.", 
               "Class E airspace begins at the ground as indicated by the blue hashed lines surrounding the area." ] },
{ "question": "Which publication contains an explanation of airport signs and markings?", 
  "answers": [ "Aeronautical Information Manual (AIM)", 
               "Advisory Circulars (AC)", 
               "Chart Supplements US" ] },
{ "question": "(Refer to Figure) In what airspace is Onawa, IA (K36) located?",
  "figure": "figure78.png",
  "answers": [ "Class G", 
               "Class E", 
               "Class D" ] },
{ "question": "Responsibility for collision avoidance in an alert area rests with", 
  "answers": [ "The controlling agency", 
               "All pilots", 
               "Air Traffic Control" ] },
{ "question": "According to 14 CFR Part 107, how may a Remote Pilot in Command (Remote PIC) operate an unmanned aircraft in Class C airspace?", 
  "answers": [ "The remote PIC must contact the ATC facility after launching the unmanned aircraft", 
               "The remote PIC must monitor the ATC frequency from launch to recovery", 
               "The remote PIC must have prior authorization from the Air Traffic Control (ATC) facility having jurisdiction over that airspace." ] },
{ "question": "(Refer to Figure) The chart shows a gray line with \"VR 1667, VR1617, VR1638 and VR1668\". Could this area present a hazard to the operations of a small unmanned aircraft?", 
  "figure": "figure59.png",
  "answers": [ "No, all operations will be above 400 feet.", 
               "Yes, the defined route provides traffic separation to manned aircraft.", 
               "Yes, this is a Military Training Route from 1500 feet AGL and below." ] },
{ "question": "(Refer to Figure) What special conditions do remote pilots need to be on the lookout while operating near Lincoln Airport?", 
  "figure": "figure52.png",
  "answers": [ "Deer near the runway", 
               "Birds in the vicinity", 
               "Parachute operations" ] },
{ "question": "When approaching holding lines from the side with the continuous lines, the pilot", 
  "answers": [ "should not cross the lines without ATC clearance", 
               "may continue taxiing", 
               "should continue taxiing until all parts of the aircraft have crossed the lines" ] },
{ "question": "The lateral dimensions of class D airspace are based on", 
  "answers": [ "the instrument procedures for which the controlled airspace is established", 
               "the number of airports that lie within Class D airspace", 
               "5 statute miles from the geographical center of the primary airport" ] },
{ "question": "(Refer to Figure) Within what airspace is Coeur D' Alene Pappy Boyington Fld located?", 
  "figure": "figure31.png",
  "answers": [ "Class B.", 
               "Class D.", 
               "Class E." ] },
{ "question": "You have received authorization to operate an sUAS at an airport. When flying the sUAS, the ATC tower instructs you to stay clear of all runways. Which situation would indicate that you are complying with this request?", 
  "answers": [ "You are on the double solid yellow line side of markings near the runway", 
               "You are on the double dashed yellow line side of markings near the runway", 
               "You are over the dashed white lines in the center of the pavement" ] },
{ "question": "When a manned aircraft is approaching to land at an airport in Class G airspace without an operating control tower, the pilot will", 
  "answers": [ "enter and fly a traffic pattern at 800 feet AGL", 
               "make all turns to the left unless otherwise indicated", 
               "fly a left-hand traffic pattern at 800 feet AGL" ] },
{ "question": "(Refer to Figure) What does the line of longitude at area 7 measure?", 
  "figure": "figure69.png",
  "answers": [ "The degrees of latitude east and west of the line that passes through Greenwich, England.", 
               "The degrees of longitude east and west of the Prime Meridian.", 
               "The degrees of longitude north and south from the equator." ] },
{ "question": "Which is true concerning the blue and magenta colors used to depict airports on Sectional Aeronautical Charts?", 
  "answers": [ "Airports with control towers underlying Class B, C, D, and E airspace are shown in blue", 
               "Airports with control towers underlying Class A, B, and C airspace are shown in blue, Class D and E airspace are magenta", 
               "Airports with control towers underlying Class C, D, and E airspace are shown in magenta" ] },
{ "question": "(Refer to Figure) The airspace surrounding the Gila Bend AF AUX Airport (GXF) (area 6) is classified as", 
  "figure": "figure75.png",
  "answers": [ "Class B", 
               "Class C", 
               "Class D" ] },
{ "question": "Under what conditions, if any, may remote pilots fly through a restricted area?", 
  "answers": [ "With the controlling agency’s authorization", 
               "When flying on airways with an ATC clearance", 
               "Regulations do not allow this" ] },
{ "question": "Which technique should a remote pilot use to scan for traffic?", 
  "answers": [ "Continuously scan the sky from right to left", 
               "Systematically focus on different segments of the sky for short intervals", 
               "Concentrate on relative movement detected in the peripheral vision area" ] },
{ "question": "Flight Data Center (FDC) NOTAMS are issued by the National Flight Data Center and contain regulatory information, such as", 
  "answers": [ "Temporary flight restrictions.", 
               "Markings and signs used at airports.", 
               "Standard communication procedures at uncontrolled airports." ] },
{ "question": "An aircraft announces that they are on short final for runway 9. Where will the aircraft be in relation to the airport?", 
  "answers": [ "North", 
               "East", 
               "West" ] },
{ "question": "(Refer to Figure area 3.) You need to operate your sUAS in close proximity to the Elizabeth City CGAS RGL (ECG) airport. What frequency should be used to contact ATC?", 
  "figure": "figure20-1.png",
  "answers": [ "122.95", 
               "120.5", 
               "124.375" ] },
{ "question": "(Refer to Figure area 6.) What airspace is Hayward Executive in?", 
  "figure": "figure74.png",
  "answers": [ "Class D", 
               "Class B", 
               "Class C" ] },
{ "question": "Public figures are protected by", 
  "answers": [ "Special use airspace", 
               "Temporary flight restrictions", 
               "Prohibited areas" ] },

{ "question": "(Refer to Figure) What is the height of the lighted obstacle approximately 6 nautical miles southwest of Savannah International?", 
  "figure": "figure23-1.png",
  "answers": [ "1548 feet MSL", 
               "1500 feet MSL", 
               "1531 feet AGL" ] },
{ "question": "(Refer to Figure) The top of the group obstruction approximately 11 nautical miles from the Savannah VORTAC on the 009-degree radial is", 
  "figure": "figure23-1.png",
  "answers": [ "454 feet MSL", 
               "400 feet AGL", 
               "432 feet MSL" ] },
{ "question": "What is required to enter an airport SIDA?", 
  "answers": [ "You must pass the TSA screening", 
               "You must have an airport issued or approved ID", 
               "You must have an FAA-issued pilot certificate" ] },
{ "question": "(Refer to Figure) What airport is located approximately 47 (degrees) 40 (minutes) N latitude and 101 (degrees) 26 (minutes) W longitude?", 
  "figure": "figure21.png",
  "answers": [ "Garrison Airport", 
               "Mercer County Regional Airport", 
               "Semshenko Airport" ] },
{ "question": "Time-critical information on airports and changes that affect the national airspace system are provided by", 
  "answers": [ "The Chart supplements US (formerly Airport/Facilities Directory or A/FD)", 
               "Advisory Circulars (ACs)", 
               "Notice to Airmen (NOTAMS)" ] },
{ "question": "You have been contracted to photograph Lake Pend Oreille from a vantage point just east of Cocolalla. You notice there is a hill at 4960 MSL which should provide good panoramic photographs. What is the maximum altitude (MSL) you are authorized to fly over the hill?", 
  "answers": [ "You cannot operate your sUAS above 400 MSL and thus cannot operate anywhere in this part of the country.", 
               "You cannot operate your sUAS without ATC permission because you will be in class E airspace above 1200 MSL.", 
               "You may operate up to 5,360 feet MSL in Class G airspace." ] },
{ "question": "(Refer to Figure) What ATC permissions are required to operate near Anderson Airport?", 
  "figure": "figure76.png",
  "answers": [ "No ATC permission is required", 
               "ATC clearance required", 
               "A waiver must be requested" ] },
{ "question": "The most comprehensive information on a given airport is provided by", 
  "answers": [ "Notice to Airmen (NOTAMs)", 
               "The Chart Supplements US (formerly Airport Facility Directory)", 
               "Terminal Area Chart (TAC)" ] },
{ "question": "What should a remote pilot do if the sUAS they are operating collides with a bird or wildlife?", 
  "answers": [ "File an accident report with the NTSB", 
               "File an accident report to the FAA", 
               "Report the collision to ATC" ] },
{ "question": "The numbers 9 and 27 on a runway indicate that the runway is oriented approximately", 
  "answers": [ "090 degrees and 270 degrees magnetic", 
               "009 degrees and 027 degrees true", 
               "090 degrees and 270 degrees true" ] },
{ "question": "(Refer to Figure area 6) Sky Way Airport is", 
  "figure": "figure71-1.png",
  "answers": [ "A non-public use airport", 
               "An airport restricted to use by private and recreational pilots", 
               "A restricted military stage field within restricted airspace" ] },
{ "question": "(Refer Figure area 5.) How would a remote PIC \"Check NOTAMs\" as noted in the CAUTION box regarding the unmarked balloon?", 
  "figure": "figure20.png",
  "answers": [ "By utilizing the B4UFLY mobile application", 
               "By obtaining a briefing via an online source such as 1800WXbrief.com", 
               "By contacting the FAA district office" ] },
{ "question": "What is the purpose of the runway/runway hold position sign?", 
  "answers": [ "Denotes intersecting runways", 
               "Denotes entrance to runway from a taxiway", 
               "Denotes area protected for an aircraft approaching or departing a runway" ] },
{ "question": "Entries into traffic patterns by manned aircraft while descending create specific collision hazards and", 
  "answers": [ "should be used whenever possible", 
               "are illegal", 
               "should be avoided" ] },
{ "question": "(Refer to Figure area 5.) The airspace overlying and within 5 miles of Barnes County Airport is", 
  "figure": "figure26.png",
  "answers": [ "Class G airspace from the surface up to but not including 700 feet AGL", 
               "Class D airspace from the surface to the floor of the overlying Class E airspace", 
               "Class E airspace from the surface to 1,200 feet MSL" ] },
{ "question": "What information is contained in the Notices to Airman Publication (NTAP)?", 
  "answers": [ "All current NOTAMs", 
               "Current NOTAM (D) and FDC NOTAMs", 
               "Current FDC NOTAMs" ] },
{ "question": "Guy wires which support antenna towers can extend horizontally. Therefore, the towers should be avoided horizontally by at least", 
  "answers": [ "2,000 feet horizontally", 
               "300 feet horizontally", 
               "1,000 feet horizontally" ] },
{ "question": "(Refer to Figure) What does the line of latitude at area 4 measure?", 
  "figure": "figure26.png",
  "answers": [ "The degrees of latitude east and west of the Prime Meridian", 
               "The degrees of longitude east and west of the line that passes through Greenwich, England.", 
               "The degrees of latitude north and south from the equator" ] },
{ "question": "Which statement about longitude and latitude is true?", 
  "answers": [ "Lines of longitude cross the Equator at right angles", 
               "Lines of longitude are parallel to the Equator", 
               "The 0-degree line of latitude passes through Greenwich, England" ] },
{ "question": "When turning onto a taxiway from another taxiway, what is the purpose of the taxiway directional sign?", 
  "answers": [ "Indicates designation and direction of taxiway leading out of an intersection", 
               "Indicates direction to take off runway", 
               "Indicates designation and direction of exit taxiway from runway" ] },
{ "question": "(Refer to Figure area 1.) How close can the Remote PIC fly their sUAS to the Majors airport (GVT) without having to contact ATC?", 
  "figure": "figure24-1.png",
  "answers": [ "4 Statute Miles (SM)", 
               "Remote PICs must contact ATC whenever operating within the magenta shading on Sectional Charts.", 
               "4 Nautical Miles (NM)" ] },
{ "question": "According to 14 CFR Part 107, the remote PIC of a small unmanned aircraft planning to operate within in Class C airspace", 
  "answers": [ "is required to file a flight plan", 
               "is required to receive ATC authorization", 
               "must use a visual observer" ] },
{ "question": "(Refer to Figure) What is the latitude and longitude location of the Elizabeth City CGAS RGL (ECG)?", 
  "figure": "figure20.png",
  "answers": [ "N 36 degrees 16' W 76 degrees 10'", 
               "W 36 degrees 16' N 76 degrees 10'", 
               "N 37 degrees 0' W 77 degrees 10'" ] },
{ "question": "(Refer to Figure area 3.) With ATC authorization, you are operating your small unmanned aircraft approximately 4 SM southeast of Elizabeth City Regional Airport (ECG). What hazard is indicated to be in that area?", 
  "figure": "figure20.png",
  "answers": [ "High-density military operations in the vicinity", 
               "Unmarked balloon on a cable up to 3,008 feet AGL", 
               "Unmarked balloon on a cable up to 3,008 feet MSL" ] },
{ "question": "(Refer to Figure area 2.) At Coeur D'Alene, which frequency should be used as a common traffic advisory frequency (CTAF) to monitor airport traffic?", 
  "figure": "figure22.png",
  "answers": [ "122.05 MHz", 
               "122.8 MHz", 
               "135.075 MHz" ] },
{ "question": "While operating a sUAS just south of a controlled airport with authorization, ATC notifies you to stay clear of the runway 6 final approach course. What action should you take to comply with this request?", 
  "answers": [ "Stay clear of areas to the east and north of your area of operation", 
               "Stay clear of areas to the west and north of your area of operation", 
               "Stay clear of areas to the west and south of your area of operation" ] },
{ "question": "What is the purpose of the runway hold position markings on the taxiway?", 
  "answers": [ "Holds aircraft short of the runway", 
               "Allows an aircraft permission onto the runway", 
               "Identifies the area where aircrafts are prohibited" ] },
{ "question": "What should remote pilots rely on for wire strike avoidance?", 
  "answers": [ "Visual scanning", 
               "Sectional chart markings", 
               "Chart supplement US airport and airspace details" ] },
{ "question": "One of the purposes for issuing a Temporary Flight Restriction (TFR) is to", 
  "answers": [ "announce parachute jump areas", 
               "identify Airport Advisory areas", 
               "protect public figures" ] },
{ "question": "(Refer to Figure area 4.) You have been hired to inspect the tower under construction at 46.9N and 98.6W, near Jamestown Regional (JMS). What must you receive prior to flying your unmanned aircraft in this area?", 
  "figure": "figure26.png",
  "answers": [ "Authorization from ATC", 
               "Authorization from the military", 
               "Authorization from the National Park Service" ] },
{ "question": "The \"taxiway ending\" marker", 
  "answers": [ "identifies the area where aircrafts are prohibited", 
               "indicates taxiway does not continue", 
               "provides general taxiing direction to the named taxiway" ] },
{ "question": "(Refer to Figure area 5.) You are operating a sUAS in the vicinity of Sulphur Springs Airport (SLR) where there is active air traffic. Who has priority and right-of-way within the traffic pattern area?",
  "figure": "figure24-2.png",
  "answers": [ "The sUAS", 
               "The existing manned aircraft", 
               "Priority and right-of-way goes to the aircraft closest to the landing runway" ] },
{ "question": "You are conducting a sUAS operations northeast of a nearby airport. While monitoring the CTAF, an aircraft announces that it is departing runway 36 utilizing a right traffic pattern. Will the aircraft potentially conflict with your operation?", 
  "answers": [ "Yes, the aircraft may overfly northeast of the airport.", 
               "No, the aircraft will be flying on the west side of the airport.", 
               "No, the aircraft will be flying to the south of the airport." ] },
{ "question": "The FAA publication that provides the aviation community with basic flight information and Air Traffic control procedures for use in the National airspace system of the United States is the", 
  "answers": [ "Aeronautical Information Manual (AIM)", 
               "Chart Supplements US (formerly A/FD)", 
               "Advisory Circulars Checklist (AC 00-2)" ] },
{ "question": "(Refer to Figure) The floor of Class B airspace overlying Hicks Airport (T67) north-northwest of Fort Worth Meacham Field is", 
  "figure": "figure25-1.png",
  "answers": [ "at the surface", 
               "3,200 feet MSL", 
               "4,000 feet MSL" ] },
{ "question": "(Refer to Figure area 3.) What is the floor of Savannah Class C airspace at the shelf area (outer circle)? ", 
  "figure": "figure23-1.png",
  "answers": [ "1,300 feet MSL", 
               "1,300 feet AGL", 
               "1,700 feet MSL" ] },
{ "question": "The recommended entry position for manned aircraft to enter an airport traffic pattern is", 
  "answers": [ "45 degrees to the base leg just below traffic pattern altitude", 
               "to cross directly over the airport at traffic pattern altitude and join the downwind leg", 
               "to enter 45 degrees at the midpoint of the downwind left at traffic pattern altitude" ] },
{ "question": "(Refer to Figure) You have been hired by a farmer to use your small unmanned aircraft to inspect his crops. The area that you are to survey is in the Devil's Lake west MOA, east of area 2. How would you find out if the MOA is active?", 
  "figure": "figure21.png",
  "answers": [ "Refer to the legend for special use airspace phone number", 
               "This information is available in the small UAS database", 
               "Refer to the Military Operations Directory" ] },
{ "question": "(Refer to Figure area 2.) While monitoring the Cooperstown CTAF you hear an aircraft announce that they are midfield left downwind to RWY 13. Where would the aircraft be relative to the runway?", 
  "figure": "figure26.png",
  "answers": [ "The aircraft is South", 
               "The aircraft is East", 
               "The aircraft is West" ] },
{ "question": "Holding position signs have", 
  "answers": [ "White inscriptions on a red background.", 
               "Red inscriptions on a white background.", 
               "Yellow inscriptions on a red background." ] },
{ "question": "What is the purpose of the No Entry Sign?", 
  "answers": [ "Identifies the area that doesn’t continue beyond the intersection", 
               "Identifies the exit boundary for the runway protected area", 
               "Identifies a paved area where aircraft are prohibited from entering" ] },
{ "question": "(Refer to Figure area 2.) Operating a sUAS, can you vertically clear the obstacle on the southeast side of Winnsboro airport?", 
  "figure": "figure24-2.png",
  "answers": [ "No", 
               "UAS operations are prohibited in this area", 
               "Yes" ] },
{ "question": "(Refer to Figure area 1.) The floor of the Class E airspace above Georgetown Airport (E36) is at", 
  "figure": "figure71-2.png",
  "answers": [ "3,823 feet", 
               "the surface", 
               "700 feet AGL" ] },
{ "question": "Most midair collision accidents occur during", 
  "answers": [ "hazy days", 
               "clear days", 
               "cloudy nights" ] },
{ "question": "(Refer to Figure area 2.) Why would the small flag at Lake Drummond be important to a remote pilot?", 
  "figure": "figure20.png",
  "answers": [ "This is a GPS checkpoint that can be used for both manned and remote pilots for orientation.", 
               "This is a VFR checkpoint for manned aircraft and a higher volume of air traffic should be expected here.", 
               "This indicates that there will be a large obstruction depicted in the next printing of the chart." ] },
{ "question": "(Refer to Figure) What do the blue lines on the map below indicate throughout this sectional?", 
  "figure": "figure80.png",
  "answers": [ "Airline corridors", 
               "Military training routes", 
               "Victor Airways" ] },
{ "question": "What are the requirements for operating a sUAS in Class C airspace?", 
  "answers": [ "Two-way radio communications and transponder with altitude reporting capabilities", 
               "Two-way radio communications and visual observer", 
               "ATC authorization and visual observer" ] },
{ "question": "An FDC NOTAM will typically contain information", 
  "answers": [ "regarding public gatherings of large groups", 
               "regarding military operations", 
               "regarding available hard surface runways" ] },
{ "question": "(Refer Figure) You have been hired to fly your UA to inspect train tracks from the town of Hinton to the town of Winnebago. Will you be able to conduct this flight without contacting ATC?", 
  "figure": "figure78.png",
  "answers": [ "Yes, because you will remain under 400 feet.", 
               "No, because you will pass through the Echo airspace.", 
               "No, because you will pass through the Delta airspace." ] },
{ "question": "Checking the NOTAMs confirms the Blue Angels are scheduled to perform at the local airport. When can UAS operations resume relative to this NOTAM?", 
  "answers": [ "Once the Blue Angels have landed", 
               "With ATC authorization", 
               "Immediately, so long as a 1 NM distance is maintained" ] },
{ "question": "(Refer to Figure) Where can you find additional information about \"R-2305\"?", 
  "figure": "figure75.png",
  "answers": [ "On the Special Use Airspace section of the chart", 
               "In the Aeronautical Information Manual", 
               "In the Chart Supplements U.S. (Formerly A/FD)" ] },
{ "question": "A larger UAS is converging head-on. What should you do?", 
  "answers": [ "The smaller aircraft should adjust course to the right", 
               "The larger aircraft should adjust course to the right", 
               "Both aircraft should adjust course to the right" ] },
{ "question": "Where can you find information about operating in an MOA along your planned route of flight?", 
  "answers": [ "Sectional chart", 
               "Chart supplement", 
               "Aeronautical Information Manual" ] },
{ "question": "(Refer to Figure Area 1) The airspace overlying Tomlinson Airport is", 
  "figure": "figure26.png",
  "answers": [ "Class G up to 18,000", 
               "Class E from 1,200 up to but not including 18,000", 
               "Class E from 700 up to but not including 18,000" ] },
{ "question": "The typical outer radius limits of Class C airspace are", 
  "answers": [ "10 NM", 
               "20 NM", 
               "30 NM" ] },
{ "question": "(Refer to Figure area 2) The airspace directly overlying Addison Airport (ADS) is", 
  "figure": "figure25-2.png",
  "answers": [ "Class D up to 3,000 feet MSL", 
               "Class D up to but not including 3,000 feet MSL", 
               "Class E from the surface up to 3,000 feet MSL" ] },
{ "question": "Time-critical information on airports and changes that affect the national airspace system are provided by", 
  "answers": [ "Notices to Airmen (NOTAMS)", 
               "The Chart Supplements U.S. (formerly Airport/Facilities Directory or A/FD)", 
               "Advisory Circulars (ACs)" ] },
{ "question": "What minimum radio equipment is required for operation within Class C airspace?", 
  "answers": [ "Two-way radio communications equipment and a 4096-code transponder", 
               "Two-way radio communications equipment, a 4096-code transponder, and DME", 
               "Two-way radio communications equipment, a 4096-code transponder, and an encoding altimeter" ] },
{ "question": "What is the most effective way for a UA pilot to scan for traffic?", 
  "answers": [ "Maintain your focus on the UA and use your peripheral vision to scan small segments of the sky", 
               "A series of short regularly spaced eye movements scanning 10-degree segments of the sky", 
               "Continuously scan the sky from right to left" ] },
{ "question": "(Refer to Figure area 3.) The floor of Class B airspace at Dallas Executive (RBD) is", 
  "figure": "figure25-3.png",
  "answers": [ "at the surface", 
               "3,000 feet MSL", 
               "3,100 feet MSL" ] },
{ "question": "(Refer to Figure area 1.) The Fentress NALF Airport (NFE) is in what type of airspace?", 
  "figure": "figure20.png",
  "answers": [ "Class C", 
               "Class E", 
               "Class G" ] },
{ "question": "(Refer to Figure area 3 and legend 1.) For information about the parachute operations at Tri-County Airport, refer to", 
  "figure": "figure24.png",
  "answers": [ "notes on the border of the chart", 
               "Chart Supplements U.S", 
               "the Notices to Airmen (NOTAM) publication" ] },
{ "question": "(Refer to Figure area 6.) What type of airport is Card Airport?", 
  "figure": "figure24.png",
  "answers": [ "Public towered", 
               "Public non-towered", 
               "Private non-towered" ] },
{ "question": "An FDC NOTAM will typically contain information", 
  "answers": [ "regarding public gatherings of large groups", 
               "regarding military operations", 
               "regarding available hard surface runways" ] },
{ "question": "(Refer to Figure) You have been hired to use your small UAS to inspect the railroad tracks from Blencoe (SE of Sioux City) to Onawa. Will ATC authorization be required?", 
  "figure": "figure78.png",
  "answers": [ "Yes, Onawa is in Class D airspace that is designated for an airport", 
               "No, your entire flight is in Class G airspace", 
               "Yes, you must contact the Onawa control tower to operate within 5 miles of the airport" ] },
{ "question": "(Refer to Figure near the center of the chart.) What class of airspace is associated with SIOUX GATEWAY/COL DAY (SUX) Airport?", 
  "figure": "figure78.png",
  "answers": [ "Class B airspace", 
               "Class C airspace", 
               "Class D airspace" ] },
{ "question": "When the tower at a class D airport closes for the day, what happens to the airspace it controls?", 
  "answers": [ "reverts to a combination of G and E", 
               "does not change", 
               "reverts to E" ] },
{ "question": "(Refer to Figure area 4.) A small UA is being launched 2 NM northeast of the town of Hertford. What is the height of the highest obstacle?", 
  "figure": "figure20.png",
  "answers": [ "399 feet MSL", 
               "500 feet MSL", 
               "500 feet AGL" ] },
{ "question": "(Refer to Figure area 3.) What type of flights are being conducted as indicated by IR678?", 
  "figure": "figure26.png",
  "answers": [ "IFR military training route above 1,500 feet AGL.", 
               "VFR military training route above 1,500 feet AGL.", 
               "VFR military training route below 1,500 feet AGL." ] },
{ "question": "(Refer to Figure) What is the maximum altitude you are permitted to fly when inspecting the high-intensity towers 6 miles southwest of the Savannah/Hilton Head Airport (SAV)?", 
  "figure": "figure23.png",
  "answers": [ "1945 feet MSL", 
               "1945 feet AGL", 
               "1545 feet MSL" ] },
{ "question": "(Refer to Figure) You have been hired to inspect a farm 3 miles west of Hilton Head Airport, in what type of airspace will you be operating?", 
  "figure": "figure23.png",
  "answers": [ "Class G", 
               "Class E", 
               "Class C" ] }
];

airAbank = [
{ "correct": "B", 
  "explain": "No person may operate a small unmanned aircraft in prohibited or restricted areas unless that person has permission from the using or controlling agency, as appropriate. Reference: Sectional Chart Legend, 14 CFR 107.45" },
{ "correct": "A", 
  "explain": "Both the Aeronautical Information Manual (AIM) and the Pilot's Handbook of Aeronautical Knowledge (FAA-H-8083-25) contain explanations of airport signs and markings Reference: AIM Chapter 2, Section 3" },
{ "correct": "A", 
  "explain": "Onawa, IA (K36) is in the bottom right quadrant of the sectional excerpt. It is outside any shading or lines, which indicates the airport is in Class G airspace up to 1200 feet AGL Reference: Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "All activity within an Alert Area shall be conducted in accordance with FAA regulations, without waiver, and pilots of participating aircraft, as well as pilots transiting the area, shall be equally responsible for collision avoidance Reference: AIM 3-4-6" },
{ "correct": "C", 
  "explain": "No person may operate a small unmanned aircraft in class B, Class C, or class D airspace or within the lateral boundaries of the surface area of Class E airspace designated for an airport unless that person has prior authorization from ATC Reference: 14 CFR 107.41" },
{ "correct": "C", 
  "explain": "VFR Military training routes at and below 1500 feet AGL (will no segment above 1500) will be identified by four digit numbers, e.g. VR1351. VR above and below 1500 feet AGL (segments of these routes may be below 1500) will be identified by three digit numbers, e.g. VR 426. Small UAS must operate below 400 feet. This 4 digit Military Training Route indicates operations below 1500 feet AGL, which could present a hazard to the sUAS operations. Reference: AIM 3-5-2" },
{ "correct": "B", 
  "explain": "The chart supplement US includes airport details, including remarks unique to that airport. Figure 52 shown an abbreviated remark for Lincoln Airport \"Birds invof aipt\" Reference: Chart Supplement" },
{ "correct": "A", 
  "explain": "When approaching the holding line from the side with the continuous lines, a pilot should not cross the holding line without ATC clearance at a controlled airport, or without making sure of adequate separation from other aircraft at uncontrolled airports. Reference: AIM 2-3-5" },
{ "correct": "A", 
  "explain": "The dimensions of Class D airspace are as needed for each individual circumstance. The airspace may include extensions necessary for IFR arrival and departure paths. Reference: AIM 3-2-5" },
{ "correct": "C", 
  "explain": "The chart supplements US includes airport details, including the airspace the airport lies in. Figure 31 shows Coeur D' Alene airport within Class E airspace. Reference: Chart Supplement" },
{ "correct": "A", 
  "explain": "Runway hold markings are indicated by two double dashed and two solid yellow lines. You are considered to be on the taxiway on the double solid yellow line side while you are considered to be on the runway if on the double dashed yellow line side. Reference: AIM 2-3-4" },
{ "correct": "B", 
  "explain": "When a manned aircraft is approaching to land at an airport in Class G airspace without an operating control tower, each pilot of an airplane will make all turns to the left unless the airport displays approved light signals of visual markings indicating that turns should be made to the right (which will be detailed in the Chart Supplements US). Reference: 14 CFR 91.126" },
{ "correct": "B", 
  "explain": "The \"98\" north of area 7 is the line of longitude east and west of the line that passes through Prime Meridian (or the longitude that passes Greenwich, England). Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Refer to Appendix 1, Legend 1. Airports having control towers are shown in blue, all others in magenta. Reference: Sectional Chart Legend." },
{ "correct": "C", 
  "explain": "The GXF airport is surrounded by a dashed blue line which indicates it is within Class D airspace. Reference: Sectional Chart" },
{ "correct": "A", 
  "explain": "Restricted areas can be penetrated but only with the permission of the controlling agency. No person may operate an aircraft within a restricted area contrary to the restrictions imposed unless he/she has the permission of the using or controlling agency. Penetration of restricted areas without authorization from the using or controlling agency may be fatal to the aircraft and its occupants Reference: 14 CFR 107.45, AIM 3-4-3" },
{ "correct": "B", 
  "explain": "Effective scanning is accomplished with a series of short, regularly spaced eye movements that bring successive areas of the sky into the central visual field. Each movement that brings successive areas of the sky into the central visual field. Each movement should not exceed 10 degrees and each area should be observed at least one second to enable detection. Reference: AIM 8-1-6" },
{ "correct": "A", 
  "explain": "FDC NOTAMs are issued by the National Flight Data Center and contain regulatory information such as Temporary Flight Restrictions. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "On final approach to runway 9, the aircraft will be heading from east to west on a 090 heading. Thus aircraft of the airport. Reference: AIM 4-1-5" },
{ "correct": "B", 
  "explain": "According to the Chart, the ATC control tower frequency is 120.50 Reference: Sectional Chart Legend." },
{ "correct": "A", 
  "explain": "Hayward executive is located in Class D airspace up to but not including 1500 feet MSL as depicted by the blue segmented line surrounding it. Note that Class C begins at 1500 feet MSL in that sector and goes up to the bottom of the overlying Class B (noted by the \"T\") in the altitude description. Reference: AIM 3-2-5" },
{ "correct": "B", 
  "explain": "TFRs are imposed in order to: \
    1.	Protect persons and property in the air or on the surface from an existing or imminent flight associated hazard \
    2.	Provide a safe environment for the operation of disaster relief aircraft \
    3.	Prevent an unsafe congestion of sightseeing aircraft above an incident \
    4.	Protect the President, Vice President, or other public figures, and, \
    5.	Provide a safe environment for space agency operations. \
    Pilots are expected to check appropriate NOTAMs during flight planning when conducting flight in an area where a TFR is in effect. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Refer to Appendix 1, Legend 1. The top number, printed in bold, is the height of the obstruction above mean sea level. The second number, printed in parentheses, is the height of the obstruction above ground level. The obstruction is shown as 1548 feel MSL and 1534 feet AGL. Reference: Sectional Chart Legend" },
{ "correct": "A", 
  "explain": "Refer to Appendix 1, Legend 1. On figure 24, area 3, the group obstruction near the 009 degree radial has the word \"stacks\" below 454. The bold number (454) indicates the height of the obstruction above mean sea level. Reference: Sectional Chart Legend." },
{ "correct": "B", 
  "explain": "On-airport areas that are used for certain cargo functions, including screening, must be a security identification display area (SIDA). A SIDA is that portion of an airport within the US, specified in the security program, in which individuals must display an airport-issued or approved ID and carry out other security measures. Reference: 49 CFR 1544" },
{ "correct": "A", 
  "explain": "Graticules on sectional charts are the lines dividing every 30 minutes of latitude and every 30 minutes of longitude. Each tick mark represents one minute of latitude or longitude. Latitude increases northward, west longitude increases going westward. The Garrison (Pvt) airport is located approximately 47 degrees 40’N latitude and 101 degrees 26'W longitude. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Notice to Airmen (NOTAMs provide the most current information available) They provide time-critical information on airports and changes that affect the NAS. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The hill has a height of 4,960 MSL. Therefore, a sUAS may be flown up to 400 feet AGL which is 5,360 feet. The floor of airspace such as Class E in AGL not MSL. Reference: Sectional Chart Legend, 14 CFR 107.51" },
{ "correct": "A", 
  "explain": "Refer to Appendix 1, Legend 1. Anderson airport is in the bottom right quadrant of the sectional. The lack of shading around the airport indicates it is in Class G airspace. Small UAS operates in Class G airspace may be conducted without ATC permissions. However, remote pilots should exercise vigilance to ensure they cause no interruption to aircraft traffic. Reference: Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "The Chart Supplements US is a publication for pilots containing information about airports, seaplane bases, and heliports open to the public including communications data, navigational facilities and certain special notices and procedures. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Remote Pilots should report collisions between aircraft and wildlife so the authorities can take measures to mitigate future incidents. Reference: AIM 7-4-5" },
{ "correct": "A", 
  "explain": "The runway number is the whole number nearest one-tenth the magnetic azimuth of the centerline of the runway, measured clockwise from magnetic north. For example: 272 degrees = RWY 27; 087 degrees = RWY 9. Reference: AIM 2-3-3" },
{ "correct": "A", 
  "explain": "The “Pvt” after the airport names indicates Sky Way Airport is a restricted or non-public use airport. Reference: Sectional Chart" },
{ "correct": "B", 
  "explain": "Notice to Airmen (NOTAMs provide the most current information available) and can be found by visiting www.faa.org or obtained at a flight service station (FSS). A comprehensive weather briefing can be obtained as part of a standard preflight briefing. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Mandatory instructions signs are used to denote an entrance to a runway or critical area and areas where an aircraft is prohibited from entering. The runway holding position sign is located at the holding position on taxiways that intersect a runway or on runways that intersect other runways. Reference: AIM 2-3-8" },
{ "correct": "C", 
  "explain": "Entries into traffic patterns while descending create specific collision hazards and should be avoided. Reference: AIM 4-4-15" },
{ "correct": "A", 
  "explain": "The Barnes County Airport is depicted inside the magenta shading, which is controlled airspace from 700 feet AGL up to but not including 18,000 feet. Therefore, the airspace below 700 feet AGL is class G. Reference: AIM 3-2-1" },
{ "correct": "B", 
  "explain": "The notices to Airmen Publication (NTAP) is published by Air Traffic Publications every 28 days and contains all current NOTAM (D)s and FDC NOTAMs (except FDC NOTAMs for TFRs) available for publication. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Most skeletal structures are supported by guy wires which are very difficult to see in good weather and can be invisible at dusk or during periods of reduced visibility. These wires can extend about 1,500 feet horizontally from a structure; therefore, all skeletal structures should be avoided horizontally by at least 2,000 feet. Reference: AIM 7-5-3" },
{ "correct": "C", 
  "explain": "The \"47\" at area 4 is the line of latitude north and south from the equator. Reference: FAA-H-8083-35" },
{ "correct": "A", 
  "explain": "Meridians of longitude encircle the earth from pole to pole, and all meridians cross the equator at right angles. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The taxiway directional sign identifies the designation(s) of the intersecting taxiway(s) leading out of the intersection that a pilot would normally be expected to turn onto or hold short of. Reference: AIM 2-3-10" },
{ "correct": "C", 
  "explain": "Contact with ATC must be made when operating within Class D airport, which is indicated by the blue airport and the blue dashed line surrounding it. The radius of Class D in the case is 4 NM, which is the command standard radius, although configuration of Class D is individually tailored for some airports. Reference: Sectional Chart Legend, 14 CFR 107.41, AIM 3-2-5" },
{ "correct": "B", 
  "explain": "No person may operate a small unmanned aircraft in Class B, Class C or Class D airspace or within, the lateral boundaries of the surface area of Class E airspace designated for an airport unless that person has prior authorization from Air Traffic Control (ATC). Reference: 14 CFR 107.41" },
{ "correct": "A", 
  "explain": "To measure the latitude and longitude, begin with looking for the hatched black lines with degree numbers on them. Just southeast of ECG there is the 36 degrees latitude line (running east/ west) and the 76 degrees longitude line (running north/ south). Count the ticks on the latitude line which is approximately 16 - these are the number of minutes yielding N 36 degrees 16' (north because the airport is north of the equator). Next, count the ticks west of the longitude line. There are approximately 10, therefore this is W76 degrees 10' (west because the airport is west of the prime meridian). Reference: Sectional Chart Legend" },
{ "correct": "C", 
  "explain": "The sectional chart excerpt includes a blue box note 4 SM southeast of the ECG airport that says \"Caution: Unmarked balloon on cable to 3008' MSL. Check NOTAMs. Reference: Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "The common traffic advisory frequency (CTAF) is used for carrying out airport advisory practices and/or position reporting at an uncontrolled airport (which may also occur during hours when a tower is closed). The CTAF may be a UNICOM, MULTICOM, FSS or tower frequency and is identified in the appropriate aeronautical publications. On charts, CTAF is indicated by a solid dot with the letter \"C\" inside. When the control tower operates part time and a UNICOM frequency is provided, use the UNICOM frequency." },
{ "correct": "B", 
  "explain": "Runway 6 faces northeast on a 060 heading thus arriving aircraft will be on final approach southwest of the airport. Since you are operating south of the airport, you would want to avoid areas west (which would be closer to the final approach course) and north (closer to the airport and possibly the final approach course for runway 6) Reference: AIM 4-1-5" },
{ "correct": "A", 
  "explain": "Runway holding position markings on taxiways identify the locations on a taxiway where an aircraft is supposed to stop when it does not have clearance to proceed onto the runway. Reference: AIM 2-3-5" },
{ "correct": "A", 
  "explain": "The wire rich environment is typically below 1000 feet. Not all wires are marked and they can be nearly invisible when viewed from different angles. Remote pilots must exercise vigilance when operating near helicopters, moored balloons and others places where wires are frequently present. Reference: SAFO 10015" },
{ "correct": "C", 
  "explain": "TFRs are imposed in order to: \
    1.	Protect persons and property in the air or on the surface from an existing or imminent flight associated hazard \
    2.	Provide a safe environment for the operation of disaster relief aircraft \
    3.	Prevent an unsafe congestion of sightseeing aircraft above an incident \
    4.	Protect the President, Vice President, or other public figures, and, \
    5.	Provide a safe environment for space agency operations. \
    Pilots are expected to check appropriate NOTAMs during flight planning when conducting flight in an area where a TFR is in effect Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The magenta shading around Jamestown airport indicates the floor of the class E airspace starts 700 feet above the surface. No person may operate a small unmanned aircraft in class B, Class C or Class D airspace or within the lateral boundaries of the surface area of class E airspace designated for an airport unless that person has prior authorization from ATC. Reference: 14 CFR 107.41, FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Taxiway ending markers are used to indicate that the taxiway foes not continue. Reference: AIM 2-3-4 " },
{ "correct": "B", 
  "explain": "No person may operate a small unmanned aircraft that interferes with operations and traffic patterns at any airport, heliport or seaplane base. Reference: 14 CFR 107.43" },
{ "correct": "A", 
  "explain": "If taking off of runway 35, the aircraft will be departing to the north on a 360 degree heading. With right traffic, it will turn right towards the northeast on the crosswind leg. Reference: AIM 4-1-5" },
{ "correct": "A", 
  "explain": "The Aeronautical Information Manual (AIM) is the official guide to basic flight information and ATC procedures. Reference: AIM" },
{ "correct": "C", 
  "explain": "The thick blue lines on the sectional chart indicate the boundaries of the overlying Class B airspace. Within each segment, the floor and ceiling are denoted by one number over a second number or the letters SFC. The floor of the class B airspace is 4,000 feet MSL. Reference: AIM 13-2-3" },
{ "correct": "A", 
  "explain": "Within the outer magenta circle of Savannah Class C airspace, there is a number 41 directly above the number 13. These numbers depict the floor and ceiling of the Class C airspace, the floor being 1,300 feet MSL and the ceiling being 4,100 feet MSL. Reference: AIM 3-2-4" },
{ "correct": "C", 
  "explain": "The recommended entry position for an airport traffic pattern is 45 degrees to the midpoint of the downwind left at traffic pattern altitude. Reference: AIM 4-3-3" },
{ "correct": "A", 
  "explain": "A military operations area (MOA) contains military training activities such as acrobatics and calls for extreme caution. Any flight service station (FSS) within 100 miles of the area will provide, information concerning MOA hours of operation. Prior to entering an active MOA, pilots should contact the controlling agency for traffic advisories, noted in the legend for special use airspace. Reference: AIM 3-4-5" },
{ "correct": "B", 
  "explain": "Cooperstown Airport depicts one runway; RWY 13 means the aircraft will be headed 130 degrees upon landing. \"Left downwind\" means the aircraft is currently to the left side, heading opposite and midway of the landing runway. This would place the aircraft east of the landing runway. Reference: AIM 4-1-5" },
{ "correct": "A", 
  "explain": "Hold Position signs have white inscription on red background Reference: AIM 2-3-5" },
{ "correct": "C", 
  "explain": "The no entry sign prohibits an aircraft from entering an area. Typically, this sign would be located on a taxiway intended to be used in only one direction or at the intersection of vehicle roadways with runways, taxiways or aprons where the roadway may be mistaken as a taxiway or other aircraft movement surface. Reference: AIM 2-3-8" },
{ "correct": "C", 
  "explain": "The elevation of the top of the obstacle is shown as 903 feet above mean sea level (MSL). Small UAS operations may not exceed 400 AGL. Moreover, the sUAS may be operated higher than 400 feet AGL if the sUAS is flown within a 400-foot radius of the structure and doesn’t not fly higher than 400 feet above the structure's immediate uppermost limit. Reference: Sectional Chart Legend, 14 CFR 107.51" },
{ "correct": "A", 
  "explain": "Georgetown Airport is outside the magenta shaded area, which indicates the floor of Class E airspace is at 1,200 feet AGL. The airport elevation is given in the airport data as 2,623 feet MSL. Therefore, the class E airspace above Georgetown Airport is 3,823 feet MSL (2,623 +1,200). Reference: Sectional Chart" },
{ "correct": "B", 
  "explain": "The FAA near mid-air collision report indicates that 81% of the incidents occurred in clear skies and unrestricted visibility conditions. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "The flag symbol represents a visual checkpoint used by manned aircraft to identify the position to initiate their contact with Norfolk approach control. As a defined checkpoint, a higher volume of air traffic should be expected there Reference: Sectional Chart Legend, FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The routes established between VORs are depicted by blue-tinted bands showing the airway number following the letter \"V\", and are called \"Victor airways\". Remote pilots should exercise vigilance in looking for other aircraft when operating near these high-density areas. Reference: Sectional Chart Legend" },
{ "correct": "A", 
  "explain": "Operations within Class C airspace requires two-way radio communications, a transponder, and an encoding altimeter. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Notices to Airmen (NOTAMs) provide time-critical aeronautical information either temporary in nature or not sufficiently known in advance to permit publication on aeronautical charts or in other operational publications. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The town of Hinton is north of Sioux City airport. Winnebago is south of Sioux City airport. This route is through the Class D airspace, depicted with the dashed blue line. You will need to contact ATC before conducting this flight. Reference: Sectional Chart Legend" },
{ "correct": "A", 
  "explain": "A NOTAM may be issued for reasons including hazards, such as air shows. The NOTAM will include the location and time for the affected region. UAS operations should stay away from these locations during the timeframe defined by the NOTAM. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Restricted areas are identified on sectional charts with an \"R\" followed by a number. You can find information about restricted areas on the back of the sectional chart. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "When aircraft are approaching each other head-on, or nearly so, each pilot of each aircraft (regardless of category or size) shall alter course to the right. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Military Operations Areas (MOA) are depicted on sectional charts with a shaded, hashed magenta line.You can find information about the MOA on the back of the sectional, including times of operation, altitudes affected, and the controlling agency. Reference: AIM 3-4-5" },
{ "correct": "B", 
  "explain": "Tomlinson Airport is in the top left corner of Figure 26, and lies outside any colored circles. This indicates the airport is within Class E airspace from 1,200 feet AGL up to but not including 18,000 feet MSL. Reference: AIM 3-2-5" },
{ "correct": "A", 
  "explain": "The normal radius of the Class C outer area will be 10 NM. This is the area where separation is provided after two-way communication is established. It is only a requirement to contact ATC before entering the 10 NM Class C airspace depicted on the sectional chart. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Class D airspace is depicted with the dashed blue circle, the ceiling defined by the number in brackets. Reference: AIM 3-2-5" },
{ "correct": "A", 
  "explain": "Notices to Airmen (NOTAMs) provide the most current information available. They provide time-critical information on airports and changes that affect the NAS. Answer (B) is incorrect because the Chart Supplements U.S. is only revised every 8 weeks. Answer (C) is incorrect because the FAA systematically issues ACs to inform the aviation public of non-regulatory material. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Class C requires two-way radio communications equipment, a transponder, and an encoding altimeter. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Effective scanning is accomplished with a series of short, regularly spaced eye movements that bring successive areas of the sky into the central visual field. Each movement should not exceed 10 degrees, and each area should be observed for at least one second to enable detection. Reference: AIM 8-1-6" },
{ "correct": "B", 
  "explain": "The thick blue lines on the sectional chart indicate the boundaries of the overlying Class B airspace. Within each segment, the floor and ceiling are denoted by one number over a second number, or the letters \"SFC.\" The floor of the Dallas Executive (RBD) Class B airspace is 3,000 feet MSL. Reference: AIM 3-2-3" },
{ "correct": "B", 
  "explain": "Fentress NALF Airport (FNE) is in the middle of Areas 1, 2 and 6 on Figure 20. It is located in Class E airspace, depicted by the magenta dashed line surrounding it. Reference:  Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "Tabulations of parachute jump areas in the U.S. are contained in the Chart Supplements U.S. (formerly A/FD). Reference: Chart Supplements U.S." },
{ "correct": "C", 
  "explain": "Card Airport (located south of Figure 24, area 6) is a Private airport, indicated by \"PVT\" after the airport name and the circled \"R.\" This airport is depicted in magenta, which means it is non-towered. Reference: Sectional Chart Legend" },
{ "correct": "A", 
  "explain": "Notices to Airmen (NOTAMs) provide time-critical aeronautical information either temporary in nature or not sufficiently known in advance to permit publication on aeronautical charts or in other operational publications. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Refer to Legend 1. The entire flight for this route will be in Class G airspace. You do not need ATC authorization to operate in Class G airspace. Reference: Sectional Chart Legend" },
{ "correct": "C", 
  "explain": "Sioux Gateway/Col Day Airport (SUX) is located in Class D airspace as depicted by the blue segmented line surrounding it, up to 3,600 feet as indicated by the bracketed [36]. Reference: Sectional Chart Legend" },
{ "correct": "C", 
  "explain": "At those airports where the control tower does not operate 24 hours a day, the operating hours of the tower will be listed on the appropriate charts and in the A/FD. During the hours the tower is not in operation, the Class E surface area rules or a combination of Class E rules to 700 feet above ground level and Class G rules to the surface will become applicable. Check the A/FD for specifics. Reference: AIM 3-2-5: Class D Airspace" },
{ "correct": "C", 
  "explain": "Obstacles are depicted as an upside-down V. The top number, printed in bold, is the height of the obstruction above mean sea level (MSL). The second number in parentheses is the height of the obstruction above ground level (AGL). The highest obstacle 2 NM northeast of Hertford is 500 feet AGL. Reference: Sectional Chart Legend" },
{ "correct": "A", 
  "explain": "" },
{ "correct": "A", 
  "explain": "" },
{ "correct": "C",     
  "explain": "" },
];