loadQbank = [
{ "question": "When loading cameras or other equipment on an sUAS, mount the items in a manner that:", 
  "answers": [ "Does not adversely affect the center of gravity", 
               "Is visible to the visual observer or other crew members", 
               "Can be easily removed without the use of tools" ] },
{ "question": "Which of the following is true regarding the weight and balance of small unmanned aircraft?", 
  "answers": [ "Operations outside weight and balance limitations may result in loss of control", 
               "CG cannot change during the flight", 
               "Lateral CG is not important to small unmanned aircraft operations." ] },
{ "question": "A stall occurs when the smooth airflow over the unmanned aircraft’s wing/ propeller(s) is disrupted and the lift reduces rapidly. This is caused when the wing/ propeller (s)", 
  "answers": [ "exceeds the maximum allowable operating weight", 
               "exceeds the critical angle of attack", 
               "exceeds the maximum speed" ] },
{ "question": "Maximum endurance is obtained at the point of minimum power to maintain the aircraft", 
  "answers": [ "in a long-range descent", 
               "in steady, level flight", 
               "at its slowest possible indicated airspeed" ] },
{ "question": "When range and economy of operation are the principal goals, the remote pilot must ensure that the sUAS will be operated at the recommended", 
  "answers": [ "long-range cruise performance", 
               "specific endurance", 
               "equivalent airspeed" ] },
{ "question": "What is the best source for sUAS performance data and information?", 
  "answers": [ "Pilot report", 
               "Estimates based upon similar systems", 
               "Manufacturer publications" ] },
{ "question": "(Refer to Figure) If a sUAS weighs 10 pounds, what approximate weight would the sUAS structure be required to support during a 60 degree banked turn while maintaining altitude?", 
  "figure": "load-q7.png",
  "answers": [ "30 pounds", 
               "20 pounds", 
               "10.15 pounds" ] },
{ "question": "What effect does an uphill terrain slope have on launch performance?", 
  "answers": [ "Increases launch distance", 
               "increase launch speed", 
               "decreases launch distances" ] },
{ "question": "When operating an unmanned aircraft, the remote pilot-in-command should consider that the load factor on the wings or rotors may be increased anytime:", 
  "answers": [ "the CG is shifted rearward to the aft CG limit", 
               "the gross weight is reduced", 
               "the aircraft is subjected to maneuvers other than straight and level flight" ] },
{ "question": "The most critical conditions of launch performance are the result of some combination of high gross weight, altitude, temperature and", 
  "answers": [ "obstacles surrounding the launch site", 
               "power plant systems", 
               "unfavorable wind" ] },
{ "question": "Before each flight the remote PIC must ensure that:", 
  "answers": [ "objects carried on the sUAS are secure", 
               "ATC has granted clearance", 
               "the site supervisor has approved the flight" ] },
{ "question": "An increase in load factor will cause an unmanned aircraft to", 
  "answers": [ "have a tendency to spin", 
               "stall at a higher airspeed", 
               "be more difficult to control" ] },
{ "question": "You are operating a sUAS that does not have GPS or an installed altimeter. How can you determine the altitude you are operating?", 
  "answers": [ "Operating a second a sUAS that has an altimeter to gain a visual perspective of 400 feet from the air.", 
               "Operating the sUAS in close proximity of a tower known to be 400 feet tall.", 
               "Gaining a visual perspective of what 400 feet looks like on the ground before the flight." ] },
{ "question": "(Refer to Figure) If an unmanned airplane weighs 33 pounds, what approximate weight would the airplane structure be required to support during a 30 degree banked turn while maintaining altitude?", 
  "figure": "load-q14.png",
  "answers": [ "38 pounds", 
               "34 pounds", 
               "47 pounds" ] },
{ "question": "The angle of attack at which an airfoil stalls will", 
  "answers": [ "increase if the CG is moved forward", 
               "remain the same regardless of gross weight", 
               "change with an increase in gross weight" ] },
{ "question": "You are operating a sUAS that does not have GPS or an installed ground speed limiter. How can you determine the speed you are operating?", 
  "answers": [ "Dead reckoning", 
               "Pilotage", 
               "Wind triangle" ] },
{ "question": "The amount of excess load that can be imposed on the wing of an airplane depends upon the", 
  "answers": [ "position of the CG", 
               "speed of the airplane", 
               "abruptness at which the load is applied" ] },
{ "question": "The term \"angle of attack\" is defined as the angle", 
  "answers": [ "between the wing chord line and the relative wind",
               "between the airplane's climb angle and the horizon", 
               "formed by the longitudinal axis of the airplane and the chord line of the wing" ] },
{ "question": "What could be a consequence of operating a small unmanned aircraft above its maximum allowable weight?", 
  "answers": [ "increased maneuverability", 
               "faster speed", 
               "shorter endurance" ] },
{ "question": "How can a remote pilot determine the altitude of the terrain and structure where the flight will be conducted?", 
  "answers": [ "Manufacturer data", 
               "Road trips", 
               "Sectional chart" ] },
{ "question": "(Refer to Figure) If a sUAS weighs 50 pounds, what approximate weight would the sUAS structure be required to support during a 30 degree banked turn while maintaining altitude?", 
  "figure": "load-q21.png",
  "answers": [ "60 pounds", 
               "45 pounds", 
               "30 pounds" ] },
{ "question": "Which basic flight maneuver increases the load factor on a sUAS as compared to straight-level flight?", 
  "answers": [ "Climbs", 
               "Turns", 
               "Stalls" ] },
{ "question": "To ensure that the unmanned aircraft center of gravity (CG) limits are not exceeded, follow the aircraft loading instructions specified in the", 
  "answers": [ "Pilot's Operating Handbook or UAS Flight Manual", 
               "Aircraft Weight and Balance Handbook", 
               "Aeronautical Information Manual (AIM)" ] },
{ "question": "When operating an aircraft, the Remote PIC is responsible for using", 
  "answers": [ "weight and balance data from the factory", 
               "recent weight and balance data", 
               "the most current weight and balance data" ] },
{ "question": "According to 14 CFR Part 107, who is responsible for determining the performance of a small unmanned aircraft?", 
  "answers": [ "Manufacturer", 
               "Remote pilot-in-command", 
               "Owner or operator" ] },
{ "question": "What purpose does a rudder perform on a sUAS airplane?", 
  "answers": [ "The rudder controls yaw", 
               "The rudder controls bank", 
               "The rudder controls pitch" ] },
{ "question": "How can a remote pilot determine the altitude of the terrain and structures where the flight will be conducted?", 
  "answers": [ "Sectional chart", 
               "Manufacturers data", 
               "Road maps" ] },
{ "question": "In a 45-degree banking turn, a UAV will", 
  "answers": [ "be more susceptible to spinning", 
               "stall at a higher speed", 
               "Stall at a lower airspeed" ] },
{ "question": "A UAS loaded with the most rearward center of gravity is", 
  "answers": [ "less stable at all speeds", 
               "more stable at slow speeds", 
               "more stable at fast speeds" ] }
];

loadAbank = [
{ "correct": "A", 
  "explain": "Any mounted equipment should be balanced in a manner that does not adversely affect the center of gravity or result in unsafe performance. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Loading the aircraft outside of limitations (weight, balance, or both) may lead to moments that exceed the capabilities of the flight controls/ engine (s), thus possibly leading to loss of control or other performance anomalies? Reference: FAA-H8083-1" },
{ "correct": "B", 
  "explain": "The airfoil will stall if the critical angle of attack is exceeded. Reference: FAA-H-8083-3" },
{ "correct": "B", 
  "explain": "The maximum endurance condition is obtained at the point of minimum power required since this would require the lowest fuel flow or battery to keep the sUAS in steady, level flight. Maximum range condition occurs where the proportion between speed and power required is greatest. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Total range is dependent on both fuel available and specific range. When range and economy of operation are the principal goals, the remote pilot must ensure that the sUAS is operated at the recommended long range cruise condition. By this procedure, the sUAS will be capable of its maximum design-operating radius, or can achieve lesser flight distances with a maximum of fuel reserve at the destination Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The manufacturer is the best source of performance data and information, if available Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Refer to Figure 2 and use the following steps \
    1.	Enter the chart at a 60 degree angle of bank and proceed upward to the curved reference line. \
    1.	From the point of intersection, move to the left side of the chart and read a load factor of 2Gs. \
    2.	Multiply the aircraft weight by the load factor: 10x2=20 lbs. or working from the table 10x2.0 \
    (load factor) = 20 lbs. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The effect of runway slope on launch distance is due to the component of weight along the inclined path of the aircraft. An upslope would contribute an accelerating force component. In the case of an upslope, the retarding force component adds to drag and rolling friction to reduce the net accelerating force. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Unmanned airplane performance can be decreased due to an increase in load factor when the airplane is operated in maneuvers other than straight and level flight. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The most critical conditions of launch performance are the result of some combination of high gross weight, altitude, temperature and unfavorable wind. In all cases the remote pilot must make an accurate prediction of take-off distance from the performance data of the AFM/ POH, regardless of the runway available, and strive for polished, professional launch procedures. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Prior to each flight, the remote PIC must ensure that any object attached to or carried by the small unmanned aircraft is secure and does not adversely affect the flight characteristics or controllability of the aircraft. Reference: AC 107-2" },
{ "correct": "B", 
  "explain": "Stall speed increases in proportion to the square root of the load factor. Thus, with a load factor of 4, an aircraft will stall, at a speed which is double the normal stall speed. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "To determine altitude, with the sUAS on the ground, the remote pilot and VO should pace off 400 feet from the sUAS to get a visual perspective of the sUAS at that distance, wherein the remote pilot and VO maintain that visual perspective or closer while the sUAS is in flight. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Referencing Appendix 1, Figure 2, use the following steps: \
    1.	Enter the chart at a 30 degree angle of bank and proceed upward to the curved reference line. From the point of intersection, move to the left side of the chart and read an approximate load factor of 1.2 Gs. \
    2.	Multiply the aircraft weight by the load factor: 33*1.2=39.6 lbs. Or, working from the table: 33*1.154 \
    (load factor)= 38.1 lbs. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "When the angle of attack is increased to between 18 and 20 degrees (critical angle of attack) on most airfoils the airstream can no longer follow the upper curvature of the wing because of the excessive change in direction. The airfoil will stall if the critical angle of attack is exceeded. The airspeed at which stall occurs will be determined by weight and load factor, but the stall angle of attack is the same. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Without a GPS or manufacturer performance data, you can determine speed of the sUAS when it is flown between two or more fixed points, taking into account wind speed and direction between each point, then noting the power settings of the sUAS to operate at or less than 87 knots ground speed. This is a form of dead reckoning. Reference: FAA-H-8083-25,AC 107-2" },
{ "correct": "B", 
  "explain": "At slow speeds, the maximum available lifting force of the wing is only slightly greater than the amount necessary to support the weight of the sUAS. However, at high speeds, the capacity of the flight controls or a strong gust, may increase the load factor beyond safe limits, Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The angle of attack is the acute angle between the relative wind and the chord line of the wing. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Excessive weight reduces the flight performance in almost every respect, including a shorter endurance. In addition, operating above the maximum weight limitation can compromise the structural integrity of an unmanned aircraft. Reference: AC 107-2" },
{ "correct": "C", 
  "explain": "In addition to local resources, the sectional chart for that region should be consulted for information or the altitude of the terrain and structures. Towers and other known obstructions are depicted with their altitude noted. Reference: Sectional chart" },
{ "correct": "A", 
  "explain": "Use the following steps: \
    1.	Enter the chart at a 30 degree angle of bank and proceed upward to the curved reference line. From the point of intersection, move to the left side of the chart and read an approximate load factor of 1.2 Gs. \
    2.	Multiply the aircraft weight by the load factor: 50*1.2= 60 lbs. Or, working from the table: 50*1.154  \
    (load factor) = 57.7 lbs. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "A change in speed during straight flight will not produce any appreciable change in load but when a change is made in the sUAS flight path, an additional load is imposed upon the structure. This is particularly true if a change in direction is made at high speeds with rapid, forceful control movements. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Before any flight, verify that the unmanned aircraft is correctly loaded by determining the weight and balance condition. Review any available manufacturer weight and balance data and follow all restrictions and limitations. Reference: FAA-H-8083-1" },
{ "correct": "C", 
  "explain": "It is the responsibility of the remote PIC to use the most current weight and balance data when planning a flight and operating the sUAS. Reference: FAA-H-8083-1" },
{ "correct": "B", 
  "explain": "The remote PIC is responsible for ensuring that every flight can be accomplished safely, does not pose an undue hazard, and does not increase the likelihood of a loss of positive control. Reference: 14 CFR 107.12" },
{ "correct": "A", 
  "explain": "The purpose of the rudder is to control yaw. Answer (B) is incorrect because the ailerons control bank. Answer (C) is incorrect because pitch is controlled by the elevator. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "In addition to local resources, the sectional chart for that region should be consulted for information on the altitude of the terrain and structures. Towers and other known obstructions are depicted with their altitude noted. Reference: Sectional Chart" },
{ "correct": "B", 
  "explain": "Stall speed increases in proportion to the square root of the load factor. Thus, with a load factor of 4, an aircraft will stall at a speed which is double the normal stall speed. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Operation with the center of gravity (CG) outside the approved limits results in control difficulty. Reference: FAA-H-8083-25" },
];