operQbank=[
{ "question": "Which of the following events is considered a flyaway?", 
  "answers": [ "Unmanned aircraft does not respond to control inputs and does not execute known lost link maneuvers", 
               "Loss of the link between the Remote PIC and the unmanned aircraft", 
               "Loss of communication link between the Remote PIC and ATC" ] },
{ "question": "Fatigue can be either", 
  "answers": [ "physiological or psychological", 
               "physical or mental", 
               "acute or chronic" ] },
{ "question": "A common cause of sUAS flyaway events is", 
  "answers": [ "frequency interference", 
               "loss of GPS signals", 
               "persons standing close to the control station antenna" ] },
{ "question": "You have just landed at a towered airport and the tower tells you to contact ground control when clear of the runway. You are considered clear of the runway when", 
  "answers": [ "the aircraft cockpit is clear of the hold line", 
               "the tail of the aircraft is clear of the runway edge", 
               "all parts of the aircraft have crossed the hold line" ] },
{ "question": "Which of the following sources of information should you consult first when determining what maintenance should be performed on an sUAS or its components", 
  "answers": [ "Local pilot best practices", 
               "14 CFR Part 107", 
               "Manufacturer guidance" ] },
{ "question": "What is the best way for the remote PIC to minimize the risk of radio frequency interference during sUAS operations?", 
  "answers": [ "Never transmit on aviation frequency ranges during flight operations", 
               "Monitor frequency use with a spectral analyzer", 
               "Avoid the use of cell phones in the vicinity of the control station" ] },
{ "question": "Under what condition should the operator of a small unmanned aircraft establish a scheduled maintenance protocol?", 
  "answers": [ "When the manufacturer does not provide a maintenance schedule", 
               "When the FAA requires you to, following an accident", 
               "Small unmanned aircraft systems do not require maintenance" ] },
{ "question": "During the preflight inspection who is responsible for determining whether the aircraft is safe for flight?", 
  "answers": [ "The owner or operator", 
               "The remote pilot-in-command", 
               "The certificate mechanic who performed the annual inspection" ] },
{ "question": "Which would most likely result in hyperventilation", 
  "answers": [ "The excessive consumption of alcohol", 
               "Emotional tension, anxiety, or fear", 
               "An extremely slow rate of breathing and insufficient oxygen" ] },
{ "question": "Upon GPS signal loss, the remote Pilot should immediately", 
  "answers": [ "contact ATC and declare an emergency", 
               "perform the planned lost link contingency procedure", 
               "operate the sUAS normally, noting to account for any mode or control changes that occur if GPS is lost" ] },
{ "question": "After landing at a tower-controlled airport, a pilot should contact ground control", 
  "answers": [ "when advised by the tower", 
               "prior to turning off the runway", 
               "after reaching a taxiway that leads directly to the parking area" ] },
{ "question": "What action should the remote PIC take upon GPS signal loss?", 
  "answers": [ "Perform the planned flyaway emergency procedure", 
               "Follow normal sUAS operational procedure, noting any mode or control changes that normally occur if GPS is lost.", 
               "Land the unmanned aircraft immediately prior to loss of control" ] },
{ "question": "Which will almost always affect your ability to fly?", 
  "answers": [ "Prescription analgesics and antihistamines", 
               "Over-the-counter analgesics and antihistamines", 
               "Antibiotics and anesthetic drugs" ] },
{ "question": "What antidotal phrase can help reverse the hazardous attitude of “anti-authority”?", 
  "answers": [ "Rules do not apply to this situation", 
               "I know what I am doing", 
               "Follow the rules" ] },
{ "question": "Which of the following lithium batteries should not be used", 
  "answers": [ "A battery with a bulge on one of the sides of its case", 
               "A partially discharged battery that is warm from recent prior use", 
               "A new battery that has only been charged once, several charging cycles are required prior to normal use." ] },
{ "question": "The responsibility for ensuring that an sUAS is maintained in an airworthy condition is primarily that of the", 
  "answers": [ "Owner or operator", 
               "Remote pilot-in-command", 
               "mechanic who performs the work" ] },
{ "question": "When flying HAWK N666CB, the proper phraseology for initial contact with Whitted ATC Tower is", 
  "answers": [ "Whitted, HAWK SIX SIX SIX CEE BEE requesting to operate within Class D, west of the field.", 
               "Whitted Tower, HAWK SIX SIX SIX CHARLIE BRAVO five NM west of the airport, request permission to enter Class D airspace for unmanned aircraft operations below four hundred AGL, three NM west of the airport", 
               "Whitted Tower, Triple Six Charlie Bravo, five NM west, operating in Class D below four hundred AGL west of the airport" ] },
{ "question": "Who is responsible for determining whether a pilot is fit to fly for a particular flight even though he or she holds a current medical certificate", 
  "answers": [ "The FAA", 
               "The medical examiner", 
               "The Pilot" ] },
{ "question": "Fatigue can be recognized", 
  "answers": [ "as being in an impaired state", 
               "easily by an experienced pilot", 
               "by an ability to overcome sleep deprivation" ] },
{ "question": "What action should be taken by the Remote PIC during an sUAS flyaway event?", 
  "answers": [ "Immediately notify any/all crewmembers, bystanders, and ATC (if applicable)", 
               "Immediately notify the NTSB", 
               "Immediately notify any/all crewmembers, local law enforcement personnel, and bystanders" ] },
{ "question": "How should a sUAS preflight inspection be accomplished for the first flight of the day?", 
  "answers": [ "Quick walk around with a check of gas and oil", 
               "Thorough and systematic means recommended by the manufacturer", 
               "Any sequence as determined by the pilot-in-command" ] },
{ "question": "In which of the following scenarios is a remote PIC not required to perform a preflight inspection of their sUAS?", 
  "answers": [ "Preflight inspections are required before each flight. Thus us no scenario precludes such an inspection.", 
               "If the subsequent flight occurs immediately, following a flight before which an inspection was made.", 
               "Preflight inspections are only required for the first flight of the day. So any other flight does not require such an inspection." ] },
{ "question": "What is the proper response by the remote PIC if experiencing a lost link situation?", 
  "answers": [ "Wait for the unit to reestablish link while notifying local law enforcement of possible dangers to non-participants", 
               "Turning the control stations off and then back on to attempt the reestablishment of the link", 
               "Notify all available crew and ATC (if applicable) while executing the briefed lost link procedure" ] },
{ "question": "(Refer to Figure) What is the recommended communication procedure when operating in the vicinity of Cooperstown Airport?", 
  "figure": "oper-q24.png",
  "answers": [ "Broadcast intentions when 10 miles out and monitor transmissions on the CTAF//MULTICOM frequency, 122.9 MHz.", 
               "Contact UNICOM when 10 miles out on 122.8 MHz.", 
               "Circle the airport in a left turn prior to entering traffic monitoring transmissions on 122.9 MULTICOM. Frequency is always 122.9 MHz and the correct procedure is to broadcast intentions when 10 miles from the airport." ] },
{ "question": "(Refer to Figure) What is the recommended communications procedure for a landing at Currituck County Airport?",  
  "figure": "oper-q25.png",
  "answers": [ "Contact Elizabeth City FSS for airport advisory service", 
               "Transmit intentions on 122.9 MHz when 10 miles out and give position reports in the traffic pattern", 
               "Contact New Bern FSS for area traffic information" ] },
{ "question": "To avoid missing important steps, always use the", 
  "answers": [ "appropriate checklists", 
               "placarded airspeeds", 
               "airworthiness certificate" ] },
{ "question": "You have been hired as a Remote Pilot in command by local TV news with a small unmanned aircraft. You expressed a safety concern and the station manager has instructed you to “Fly First, ask questions later”.  What type of hazardous attitude does this attitude represent?", 
  "answers": [ "Invulnerability", 
               "Machoism", 
               "Impulsivity" ] },
{ "question": "The correct method of stating 4,500 feet MSL to ATC is", 
  "answers": [ "FOUR POINT FIVE", 
               "FOUR THOUSAND FIVE HUNDRED", 
               "FORTY-FIVE HUNDRED FEET MSL" ] },
{ "question": "Absence of the sky condition and visibility on an ATIS broadcast indicates that", 
  "answers": [ "weather conditions are at or above VFR minimums", 
               "the ceiling is at least 5,000 feet and visibility is 5 miles or more", 
               "the sky conditions are clear and visibility is unrestricted" ] },
{ "question": "Safety is an important element for a remote pilot to consider prior to operating an unmanned aircraft system. To prevent the final \"link\" in the accident chain, a remote pilot must consider which methodology?", 
  "answers": [ "Risk management", 
               "Crew resource management", 
               "Safety management system" ] },
{ "question": "Inbound to an airport with no tower, FSS or UNICOM in operation, a pilot should self-announce on MULTICOM frequency", 
  "answers": [ "123", 
               "122.7", 
               "122.9" ] },
{ "question": "When a stressful situation is encountered in flight, an abnormal increase in the volume of air breathed in and out can cause a condition known as", 
  "answers": [ "hyperventilation", 
               "aerosinusitis", 
               "aerotitis" ] },
{ "question": "A local TV station has hired a remote pilot to operate their small UA to cover breaking news stories. The remote pilot has had multiple near misses with obstacles on the ground and two small UAS accidents. What would be a solution for the news station to improve its operating safety culture?", 
  "answers": [ "The news station should implement a policy of no more than five crashes/ incidents within 6 months.", 
               "The news station should recognize hazardous attitudes and situations and develop standard operating procedures that emphasize safety.", 
               "The news station does not need to make any changes; there are times that an accident is unavoidable." ] },
{ "question": "As standard operating practice, all inbound and local traffic approaching or near an airport without a control tower should continuously monitor the appropriate facility from a distance of", 
  "answers": [ "25 miles", 
               "20 miles", 
               "10 miles" ] },
{ "question": "Automatic Terminal Information Service (ATIS) is the continuous broadcast of recorded information concerning", 
  "answers": [ "pilots of radar-identified aircraft whose aircraft is in dangerous proximity to terrain or to an obstruction", 
               "Non-essential information to reduce frequency congestion", 
               "Non-control information in selected high-activity terminal areas. ATIS is the continuous broadcast of recorded non-control information in selected high-activity terminal areas" ] },
{ "question": "How often is the remote PIC required to inspect the sUAS to ensure that it is in condition for safe operation?", 
  "answers": [ "Before each flight", 
               "Annually", 
               "Monthly" ] },
{ "question": "When should the battery for an unmanned aircraft be replaced?", 
  "answers": [ "Once recharged more than 10 times in the preceding 30 days", 
               "Per the guidelines of the sUAS manufacturer or the battery manufacturer, whichever is more restrictive", 
               "Per the guidelines of the sUAS manufacturer or the battery manufacturer whichever is least restrictive" ] },
{ "question": "An ATC radar facility issues the following advisory to a pilot flying on a heading of 090 degrees: \"UNMANNED AIRCRAFT OPERATIONS 3'O CLOCK, 2 MILES...\" Where should the remote PIC (also visual observer) look for this traffic in reference to the UA?", 
  "answers": [ "North", 
               "South", 
               "West" ] },
{ "question": "An ATC radar facility issues the following advisory to a manned pilot flying north in a calm wind: \"UNMANNED AIRCRAFT OPERATIONS 9'O CLOCK, 2 MILES...\" Where should the remote PIC (also visual observer) look for this traffic in reference to the UA?", 
  "answers": [ "North", 
               "East", 
               "West" ] },
{ "question": "Which statement is not correct concerning crew resource management in a sUAS operations?", 
  "answers": [ "Individuals who are exhibiting signs of hazardous attitudes should be approached about the issue", 
               "The Remote PIC and all crew members should communicate any observed hazards or concerns to one another", 
               "Crew members cannot, under any circumstances, challenge the decisions of the remote PIC" ] },
{ "question": "When setting up the location of the control station and placement of crew members for an afternoon flight, which of the following would be most appropriate for ensuring that vision is not impaired by the environment?", 
  "answers": [ "The operation should be set up so that the remote PIC and crew members can face west", 
               "The operation should be set up so that the Remote PIC and crew members are facing any reflective objects in the area", 
               "The operation should be set up so that the remote PIC and crew members can face east" ] },
{ "question": "Risk management, as part of the aeronautical decision making (ADM) process, relies on which features to reduce the risks associated with each flight", 
  "answers": [ "Situational awareness, problem recognition, and good judgment", 
               "Application of stress management and risk element procedures", 
               "The mental process of analyzing all information in a particular situation and making a timely decision on what action to take " ] },
{ "question": "Damaged lithium batteries can cause", 
  "answers": [ "a change in aircraft center of gravity", 
               "an inflight fire", 
               "increased endurance" ] },
{ "question": "Identify the hazardous attitude or characteristic a Remote Pilot in Command displays while taking risks in order to impress others", 
  "answers": [ "machoism", 
               "impulsiveness", 
               "invulnerability" ] },
{ "question": "When setting up the location of the control station and placement of crew members for a flight over snowy terrain, which of the following would be most appropriate for ensuring that vision is not impaired by the environment?", 
  "answers": [ "The operation should be set up so that the crew members are most comfortable.", 
               "The operation should be set up so that the crew members face the directions in which the terrain most closely matches the color of unmanned aircraft.", 
               "The operation should be set up so that the remote PIC and crew members will face minimum glare from the snow." ] },
{ "question": "As a pilot, flying for a long period in hot summer temperatures increases the susceptibility of dehydration since the", 
  "answers": [ "dry air at altitude tends to increase the rate of water loss from the body", 
               "moist air at altitude helps retain the body's moisture", 
               "temperature decreases with altitude" ] },
{ "question": "Scheduled maintenance should be performed in accordance with the", 
  "answers": [ "stipulations in 14 CFR Part 43", 
               "manufacturers’ suggested procedures", 
               "contractor requirements" ] },
{ "question": "When adapting crew resource management (CRM) concepts to the operation of a small unmanned aircraft, CRM must be integrated into", 
  "answers": [ "the communications only", 
               "all phases of the operation", 
               "the flight portion only" ] },
{ "question": "You are a remote pilot in command for a co-op energy service provider. You plan to use your unmanned aircraft to inspect power lines in the remote area 15 hours away from your home office. After the drive, fatigue impacts your abilities to complete your assignment on time. What kind of fatigue is this?", 
  "answers": [ "Acute fatigue", 
               "Chronic Fatigue", 
               "Exhaustion" ] },
{ "question": "Hazardous attitudes occur to every pilot to some degree at some time. What are some of these hazardous attitudes?", 
  "answers": [ "Poor risk management and lack of stress management", 
               "Poor situational awareness, snap judgments and lack of a decision-making process", 
               "Antiauthority, impulsivity, macho, resignation and invulnerability" ] },
{ "question": "When should pilots state their position on the airport when calling the tower for takeoff?", 
  "answers": [ "when departing from a runway intersection", 
               "when visibility is less than 1 mile", 
               "when parallel runways are in use" ] },
{ "question": "While preparing your sUAS for flight, you notice that one of the propeller blades has a nick. What action should you take?", 
  "answers": [ "If the nick is less than 1/4 the length of the blade, it is safe to operate without replacement.", 
               "Remove and replace the propeller; consult manufacturer guidelines for repair, if any.", 
               "Repair by filing the nick to a smooth curve or with adhesive approved for use on the propeller material." ] },
{ "question": "A visual observer notices a manned aircraft approaching the area in which a sUAS operations are taking place, flying just north of the area from west to east. What call could the remote PIC/ visual observer make on CTAF to alert the manned pilot?", 
  "answers": [ "Zephyr Hills traffic unmanned aircraft X-ray Yankee Zulu, operating five NM south of the airport at or below 400 AGL, located at the three-o clock position of the Cessna just north of our position Zephyrhills traffic.", 
               "Zephyr Hills traffic, unmanned aircraft at three o clock of manned aircraft in the area, Zephyrhills traffic.", 
               "Zephyr Hills traffic, unmanned aircraft X-ray Yankee Zulu to Cessna in the area, look for UAS at your three-o clock position, we are about a mile south as you are flying your sUAS." ] },
{ "question": "What services will a FSS provide?", 
  "answers": [ "Fuel pricing", 
               "Clearance to taxi for takeoff", 
               "Assistance during an emergency" ] },
{ "question": "The effective use of all available resources - human, hardware and information -prior to and during flight to ensure the successful outcome of the operation is called", 
  "answers": [ "risk management", 
               "crew resource management", 
               "safety management system" ] },
{ "question": "Fatigue is one of the most treacherous hazards to flight safety", 
  "answers": [ "as it may not be apparent until serious errors are made", 
               "because it results in slow performance", 
               "as it may be a function of physical robustness or mental activity" ] },
{ "question": "An extreme case of a pilot getting behind the aircraft can lead to operational pitfall of", 
  "answers": [ "loss of workload", 
               "loss of situational awareness", 
               "Internal stress" ] },
{ "question": "During your preflight inspection, you discover that the casing of your sUAS battery has expanded beyond its normal dimensions. What actions will you take?", 
  "answers": [ "Throw it away with your household trash", 
               "Follow the manufacturer's guidance", 
               "Use it as long as it will still hold a charge" ] },
{ "question": "The Common Traffic Advisory Frequency (CTAF) is used for manned aircraft to", 
  "answers": [ "announce ground and flight intentions", 
               "request air traffic control clearance", 
               "request fuel services" ] },
{ "question": "(Refer to Figure) At Coeur D'Alene, which frequency should be used as a Common Traffic Advisory Frequency (CTAF) to monitor airport traffic (use the next two images for this question)?", 
  "figure": "oper-q60.png",
  "answers": [ "122.05 MHz", 
               "135.075 MHz", 
               "122.8 MHz" ] },
{ "question": "The accurate perception and understanding of all the risk element factors and conditions is", 
  "answers": [ "situational awareness", 
               "judgment", 
               "aeronautical decision making" ] },
{ "question": "What is the best way to mitigate risk?", 
  "answers": [ "SMS plan", 
               "Weekly meetings", 
               "Establishing an operational procedure guideline" ] },
{ "question": "What can help a pilot mitigate stress?", 
  "answers": [ "Increasing stress tolerance", 
               "Removing stress from personal life", 
               "Breathing into a paper bag" ] },
{ "question": "What can affect your performance?", 
  "answers": [ "Prescription medications", 
               "Over the counter medications", 
               "Over the counter and prescribed medications" ] },
{ "question": "The aircraft call sign N169US will be spoken in this way:", 
  "answers": [ "November one six niner uniform sierra", 
               "November one six niner unmanned system", 
               "November one hundred sixty-nine uniform sierra" ] },
{ "question": "What antidotal phase can help reverse the hazardous attitude of impulsivity?", 
  "answers": [ "It could happen to me", 
               "Do it quickly to get it over with", 
               "Not so fast, think fast" ] },
{ "question": "What action should the operator of a sUAS take if the manufacturer does not provide information about scheduled maintenance?", 
  "answers": [ "The operator should contact the FAA for a minimum equipment list", 
               "The operator should establish a scheduled maintenance protocol", 
               "The operator should contact the NTSB for component failure rates for their specific a sUAS" ] },
{ "question": "(Refer to Figure area 1.) After receiving authorization from ATC to operate a small UA near Minot International airport (MOT) while the control tower is operational, which radio communication frequency could be used to monitor manned aircraft and ATC communications?", 
  "figure": "figure21.png",
  "answers": [ "UNICOM 122.95", 
               "ASOS 118.725", 
               "CT-118.2" ] },
{ "question": "What precautions should a remote PIC take to prevent possible inflight emergencies when using lithium-based batteries?", 
  "answers": [ "Store the batteries in a freezer to allow proper recharging", 
               "Follow the manufacturer's recommendations for safe battery handling", 
               "Allow the battery to charge until it reaches a minimum temperature of 100 degrees C" ] },
{ "question": "Aeronautical decision making (ADM) can be described as the pilot's ability for", 
  "answers": [ "Sound judgment and good decision making.", 
               "Making quick decisive actions.", 
               "Interpreting dangerous situations." ] }
];

operAbank=[
{ "correct": "A", 
  "explain": "A flyaway is when the sUAS becomes uncontrollable and does not operate in a manner that would be expected in a normal or lost link flight situation. Reference: 14 CFR Part 107" },
{ "correct": "C", 
  "explain": "Fatigue can be either acute (short-term) or chronic (long-term). Acute fatigue, a normal occurrence of everyday living, is the tiredness felt after long periods of physical and mental strain, including strenuous muscular effort, immobility, heavy mental workload, strong emotional pressure, monotony, and lack of sleep. Chronic fatigue occurs when there is not enough time for a full recovery from repeated episodes of acute fatigue. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Frequency interference is one of the most common causes of flyaways; therefore, remote PICs should assess the risk of such interference prior to and during flight. Extra caution is necessary when operating in the vicinity of other a sUAS. The loss of GPS may degrade the sUAS capabilities slightly but should not cause a flyaway. It is not unusual for people to stand near the control station; it is highly unlikely for this to cause a flyaway. Reference: AC 107-2" },
{ "correct": "C", 
  "explain": "An aircraft exiting a runway is not clear of the runway until all parts of the aircraft have crossed the applicable holding position marking. Reference: AIM 2-3-5" },
{ "correct": "C", 
  "explain": "The preferred source of information is the manufacturer's guidance about maintenance schedule and instructions, Reference: AC 107-2" },
{ "correct": "B", 
  "explain": "Remote PICs should monitor the appropriate aviation frequency such as CTAF during flight operations and make announcement concerning a sUAS operations as appropriate. Some a sUAS require the use of cellphone or tablet computers for operation, therefore are acceptable for use in most cases. The best way to avoid frequency interference is to check local frequency spectrum use prior to flight and continue to monitor such use during flight by utilizing a frequency spectrum analyzer. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Follow all manufacturer maintenance recommendations to achieve the longest safest service life of the sUAS. If the sUAS or component manufacturer does not provide scheduled maintenance instructions, it is recommended that you establish your own scheduled maintenance protocol. Reference: AC 107-2" },
{ "correct": "B", 
  "explain": "The remote PIC is responsible for determining whether that aircraft is in condition for safe flight. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Hyperventilation is most likely to occur during period of stress or anxiety Reference: AIM 8-1-3" },
{ "correct": "C", 
  "explain": "Most a sUAS are designed to fly normally with minimal impact on features or controllability if GPS signals are degraded or lost. Loss of GPS is not an emergency and is not considered to be a loss of link between the unmanned aircraft and the control station. If the failure of GPS does result in a flyaway or other dangerous situation, it should be treated as an emergency. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "A pilot who has just landed should not change from the tower frequency to the ground control frequency until directed to do so by the controller Reference: AIM 4-3-14" },
{ "correct": "B", 
  "explain": "Most a sUAS are designed to fly normally with minimal impact on features or controllability if GPS signals are degraded or lost. Loss of GPS is not an emergency and is not considered to be a loss of link between the unmanned aircraft and the control station. If the failure of GPS does result in a flyaway or other dangerous situation, it should be treated as an emergency. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Pilot performance can be seriously degraded by both prescribed and over-the-counter medications, as well as by the medical conditions for which they are taken. Flying is almost always precluded while using prescription analgesics since these drugs may cause side effects such as mental confusion, dizziness, headaches, nausea, and vision problems. Depressants, including antihistamines, lower blood pressure, reduce mental processing and slow motor and reaction responses. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "The antiauthority (don’t tell me) attitude is found in people who do not like anyone telling them what to do. The antidote for this attitude is: follow the rules, they are usually right. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Damaged batteries should never be used or charged. Lithium batteries do normally get warm during discharge. Avoid the use of hot batteries. New batteries should be treated per manufacturing instructions, but do not normally need several charge cycles to use. Reference: SAFO 10017" },
{ "correct": "B", 
  "explain": "No person may operate a sUAS unless it is in a condition for safe operation. Prior to each flight, the remote pilot-in-command must check the sUAS to determine whether it is in a condition for safe operation. No person may continue flight of the small unmanned aircraft when he or she knows or has reason to know that the small unmanned aircraft system is no longer in a condition for safe operation Reference: 14 CFR 107.15" },
{ "correct": "B", 
  "explain": "The term \"initial radio contact\" or \"initial call-up\" means the first radio call you make to a given facility, or the first call to a different controller or Flight Service specialist within a facility. Use the following format: \
    1.	Name of the facility being called \
    2.	You full aircraft identification as filed in the flight plan \
    3.	Type of message to follow or your request if it is short \
    4.	The word \"over\" if required (typically omitted, except for communications via a remote \
    communication outlet or in cases when it is necessary to confirm the end of a transmission \
    Example: New York Radio, Mooney Three One One Echo, over \
    When the aircrafts manufacturer's name or model is stated, the prefix \"N\" is dropped. The first two characters of the call sign may be dropped only after ATC calls you by your last three numbers Reference: AIM 4-2-3" },
{ "correct": "C", 
  "explain": "The pilot is responsible for determining whether he or she is fit to fly for a particular flight Reference: FAA-H-8083-25" },    
{ "correct": "A", 
  "explain": "The fatigues pilot is an impaired pilot, and flying requires unimpaired judgment. Reference: FAA-H-8083-2" },
{ "correct": "A", 
  "explain": "During a flyaway event a sUAS may not react in ways that can be expected or predicted thus this is an emergency situation. The remote PIC should immediately communicate this emergency to crew members and ATC (if applicable) as well as any persons in the immediate area so as to minimize risk for injury. There is no obligation to contact the NTSB or law enforcement during a flyaway. Reference: 14 CFR 107.19, 107.21" },
{ "correct": "B", 
  "explain": "The preflight inspection should be a thorough and systematic means by which the remote PIC determines that the sUAS is ready for safe flight. Most aircraft flight manuals or Pilot's operating handbooks contain a section on preflight inspection that should be used for guidance in this Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The remote PIC must inspect the sUAS before each flight Reference: 14 CFR 107.49" },
{ "correct": "C", 
  "explain": "All participants in the sUAS operation and ATC (if operating within or near controlled airspace) should be notified of the lost link situation, an emergency should be declared. There is no obligation to contact law enforcement. It is never recommended to turn off the control station when the UA engines are running or if it is in flight. Reference: AC 107-2, 14 CFR 107.21" },
{ "correct": "A", 
  "explain": "MULTICOM frequency is always 122.9 MHz and the correct procedure is to broadcast intentions when 10 miles from the airport Reference: AIM 4-1-9" },
{ "correct": "B", 
  "explain": "When there is no tower, Flight service, or UNICOM station on the airport use MULTICOM frequency 122.9 for self-announce procedures. Such airports will be identified in the appropriate aeronautical information publications. Reference: AIM 4-1-9" },
{ "correct": "A", 
  "explain": "To avoid missing important steps, always use the appropriate checklists whenever, they are available. Consistent adherence to approved checklists is a sign if a disciplined and competent pilot. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Impulsivity, as a hazardous attitude, has the motto \"Do it quickly\" The person frequently feels the need to do something, anything, immediately. He or she does not stop to think about the best alternative and does the first thing that comes to mind. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Up to but not including 18,000 feet MSL, state the separate digits of the thousands, plus the hundreds, if appropriate. Example: \"4,500-four thousand, five hundred\" Reference: AIM 4-2-9" },
{ "correct": "B", 
  "explain": "The absence of a sky condition or ceiling and/or visibility on ATIS indicates a ceiling of 5,000 feet or above and visibility of 5 miles or more. Reference: AIM 4-1-13" },
{ "correct": "A", 
  "explain": "Risk management is the part of the decision making process that relies on situational awareness, problem recognition, and good judgment to reduce the risks associated with each flight. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Where there is no tower or UNICOM station on the airport, use MULTICOM frequency 122.9 for self-announce procedures. Reference: AIM 4-1-9" },
{ "correct": "A", 
  "explain": "An abnormal increase in the volume of air breathed in and out of the lungs flushes an excessive amount of carbon dioxide from the lungs and blood, causing hyperventilation Reference: AIM 8-1-3" },
{ "correct": "B", 
  "explain": "A culture of safety must be established with all commercial a sUAS operations. This safety culture may use a number of techniques including situational awareness, risk based aeronautical decision making (ADM) crew resource management (CRM) and safety management systems (SMS) Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Pilots of inbound traffic should monitor and communicate as appropriate on the designated CTAF from 10 miles to landing. Pilots of departing aircraft should monitor/ communicate on the appropriate frequency from start-up, during taxi and until 10 miles from the airport unless the regulations or local procedures require otherwise. Refere1nce: AIM 4-1-9" },
{ "correct": "C", 
  "explain": "ATIS is the continuous broadcast of recorded non-control information in selected high activity terminal areas Reference: AIM 4-1-13" },
{ "correct": "A", 
  "explain": "The remote PIC must inspect the sUAS before each flight Reference: 14 CFR 107.49" },
{ "correct": "B", 
  "explain": "Follow all manufacturer maintenance recommendations to achieve the longest safest service life of the sUAS. By abiding by the more restrictive limitation or component life cycle the remote PIC will be assured of being in compliance of both the sUAS and battery manufacturers' guidelines Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Traffic information will be given in azimuth from the aircraft in terms of the 12 hour clock. Thus each hour would constitute an angle of 30 degrees. If an aircraft is proceeding on a heading of 090 degrees(east) traffic located at 3'o clock position would be 90 degrees right of the nose, south of the aircraft. If the sUAS is being operated to the south of the aircraft, the aircraft itself is to the north of the operation. Reference: AIM 4-1-15" },
{ "correct": "B", 
  "explain": "An aircraft flying north in calm wind would be heading 360 degrees. When advised of traffic at the 9 O’clock position, the pilot should look 90 degrees left of the nose, to the west but the Remote PIC and a sUAS need to look to the east as they are to the west of the manned aircraft Reference: AIM 4-1-15" },
{ "correct": "C", 
  "explain": "Crew members should express any and all concerns about decisions of the remote PIC or other crew members at any time. Clearly, the remote PIC is in charge, but that doesn’t not always make them right or invulnerable to errors, omissions, or other potentially hazardous instances Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "If the operation is to take place in the afternoon, the sun will be setting towards the west and could impair the vision of those participating in the sUAS operation. Thus, when practical, the operation should be set up to minimize the impact of the sun on being able to maintain the visual line of sight with the unmanned aircraft Reference: FAA-H-8083-25, 14 CFR 107.31" },
{ "correct": "A", 
  "explain": "Risk management is the part of the decision making process that relies on situational awareness, problem recognition, and good judgment to reduce the risks associated with each flight. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Both lithium metal and lithium-ion batteries are highly flammable and capable of self-ignition when a battery short circuits or is overcharged, heated to extreme temperature, mishandled or otherwise defective Reference: SAFO 10017" },
{ "correct": "A", 
  "explain": "Machoism, as a hazardous attitude, has the motto \"I can do it, I'll show them\" The person tries to prove that he or she is better than anyone else. The person takes risks to impress others. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "If the operation is to take place in snow covered environment, awareness concerning how this may impact vision, such as a glare or the ability to see and operate the unmanned aircrafts against a featureless background. Thus, when practical, the operation should be set up to minimize the impact of the sun on being able to maintain the visual line of sight with the unmanned aircraft Reference: FAA-H-8083-25, 14 CFR 107.31" },
{ "correct": "A", 
  "explain": "As a pilot, flying for long periods in hot summer temperatures or at high altitudes increases the susceptibility of dehydration since the dry air at altitude tends to increase the rate of water loss from the body. If this fluid is not replaced, fatigue progresses to dizziness, weakness, nausea, tingling of hands and feet, abdominal cramps, and extreme thirst. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Follow all manufacturer maintenance recommendations to achieve the longest and safest service life of the sUAS. If the sUAS or component manufacturer does not provide scheduled maintenance instructions, it is recommended that you establish your own scheduled maintenance protocol. Reference: AC 107-2" },
{ "correct": "B", 
  "explain": "Crew resource management is the effective use of all available resources - human, hardware and information - prior to and during flight to ensure a successful outcome of the operation. The remote PIC must integrate crew resource management techniques into all phases of the sUAS operation. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Acute fatigue is short term and is normal occurrence in everyday living. It is the kind of tiredness people feel after a period of strenuous effort, excitement, or lack of sleep." },
{ "correct": "C", 
  "explain": "ADM addresses the following five hazardous attitudes. Antiauthority (don’t tell me) impulsivity (do something quickly) invulnerability (it won’t happen to me) machoism (I can do it) resignation (what’s the use) Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Pilots should state their position on the airport, when calling the tower for takeoff from a runway intersection Reference: AIM 4-3-10" },
{ "correct": "B", 
  "explain": "When in doubt, remove and replace any damaged part. If repair is allowed, it should be outlined by the manufacturer. Remote PICs should consult with the manufacturer about such repair. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Using standard phraseology, remote PICs/ crew should clearly communicate the position of the sUAS operation in relation to a known geographic location and any other information that may help the manned aircraft be aware of and avoid conflicting with the a sUAS Reference: AIM 4-1-15, AC 107-2" },
{ "correct": "C", 
  "explain": " Flight Service Stations (FSS's) are air traffic facilities that provide pilot briefings, enroute communications and VFR search-and-rescue services, assist lost aircraft and aircraft in emergency situations, relay ATC clearances, originate notice to Airmen, broadcast aviation weather and NAS information, receive and process IFR flight plans, and monitor NAVAIDs. In addition, FSS's take weather observations, issue airport advisories, advise customs and immigration of transborder flights, and provide En route flight advisory service (Flight watch) (in Alaska only) Reference: AIM 4-1-3" },
{ "correct": "B", 
  "explain": "Crew resource management is the effective use of all available resources - human, hardware and information - prior to and during flight to ensure a successful outcome of the operation. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "Fatigue is one of the most treacherous hazards to flight safety as it may not be apparent to a pilot until serious errors are made Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Getting behind the aircraft or falling can result in not knowing where you are, an inability to recognize deteriorating circumstances, and/or the misjudgment of the rate of deterioration Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Your first action should be to seek out the manufacturer's guidance about replacement or disposal. Do not use damaged batteries, as they may self-ignite during flight or if charged. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "CTAF is designed for the purpose of carrying out airport advisory practices and/or position reporting at an uncontrolled airport (which may also occur during hours when a tower is closed). The CTAF may be a UNICOM, MULTICOM, FSS, or tower frequency and is identified in the appropriate aeronautical publications. On the sectional chart, a solid dot with the letter \"C\" inside indicates Common Traffic Advisory Frequency. When the control tower operates part time and a UNICOM frequency is provided, use the UNICOM frequency. Reference: AIM 4-1-9" },
{ "correct": "C", 
  "explain": "CTAF is a frequency designed for the purpose of carrying out airport advisory practices and/or position reporting at an uncontrolled airport (which may also occur during hours when a tower is closed). The CTAF may be a UNICOM, MULTICOM, FSS, or tower frequency and is identified in the appropriate aeronautical publications. A solid dot with the letter \"C\" inside indicates CTAF. When the control tower operates part time and a UNICOM frequency is provided, use the UNICOM frequency. Reference: AIM 4-1-9" },
{ "correct": "A", 
  "explain": "Situational awareness is the accurate perception and understanding of all the factors and conditions within the five fundamental risk elements (flight, pilot, aircraft, environment, and type of operation that comprise any given aviation situation) that affect safety before, during, and after the flight. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "To fly safely, the pilot needs to assess the degree of risk and determine the best course of action to mitigate the risk. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "There are several techniques to help manage the accumulation of life stresses and prevent stress overload. For example, to help reduce stress levels, set aside time for relaxation each day or maintain a program of physical fitness. To prevent stress overload, learn to manage time more effectively to avoid pressure imposed by getting behind schedule and not meeting deadlines. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Virtually all medications have the potential for adverse side effects in some people. Reference: FAA-H-8083-25 " },
{ "correct": "A", 
  "explain": "Aircraft call signs should be spoken in their entirety, using the phonetic alphabet. Numbers are spoken individually. Reference: AIM 4-2-3" },
{ "correct": "C", 
  "explain": "Impulsivity (do something quickly!) is the attitude of people who frequently feel the need to do something, anything, immediately. They do not stop to think about what they are about to do, they do not select the best alternative, and they do the first think that comes to mind. The antidote for this attitude is: Not so fast. Think first. (PLT103) - FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Follow all manufacturer maintenance recommendations to achieve the longest and safest service life of the sUAS. If the sUAS or component manufacturer does not provide scheduled maintenance instructions, it is recommended that you establish your own scheduled maintenance protocol. Reference: AC 107-2" },
{ "correct": "C", 
  "explain": "Minot International airport (MOT) is in Class D airspace, depicted by the dashed blue lines. You should monitor the Control Tower frequency 118.2 to hear manned aircraft and ATC communications operating in this vicinity. Answer (A) is incorrect because the UNICOM frequency will only provide airport activity information when the control tower is not operating. Answer (B) is incorrect because the ASOS frequency will provide weather information for that airport but not activity information. Reference: Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "Lithium-based batteries are highly flammable and capable of ignition. A battery fire could lead to an in-flight emergency by causing a loss of control of the small UA. Lithium battery fires can occur when a battery short-circuits, is improperly charged, is heated to extreme temperatures, is damaged as a result of a crash, is mishandled, or is simply defective. The remote PIC should follow the manufacturer's recommendations to help ensure safe battery handling and usage. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "ADM provides a structured, systematic approach to analyzing changes that may occur during a flight and how these changes might affect the safe outcome of that flight. The ADM process addresses all aspects of decision making for the crew and identifies the steps involved in good decision making.    " },
];