regsQbank = [
{ "question": "A professional wildlife photographer operates an sUAS from a moving truck to capture aerial images of migrating birds in remote wetlands. The driver of the truck does not serve any crew member role in the operation. Is this sUAS operation in compliance with 14 CFR Part 107?", 
  "answers": [ "Compliant with Part 107", 
               "Not compliant with Part 107", 
               "Not compliant with state and local traffic laws" ] },
{ "question": "Remote Pilots are required to complete the following operational area surveillance prior to the sUAS flight:", 
  "answers": [ "Make a plan to keep non-participants in viewing distance for the whole operation", 
               "Select an operational area that is populated", 
               "Keep the operational area free of and at an appropriate distance from all non-participants" ] },
{ "question": "Personnel at an outdoor concert venue use an sUAS to drop promotional t-shirts and CDs over the audience. Is this sUAS operation in compliance with 14 CFR 107?", 
  "answers": [ "No, unless authorized by the venue", 
               "Yes, compliant with Part 107", 
               "Not compliant with Part 107" ] },
{ "question": "Which of the following crewmembers must be used during Part 107 sUAS operations?", 
  "answers": [ "Remote PIC", 
               "Remote PIC, Visual Observer", 
               "Remote PIC, Visual Observer, Person manipulating the controls" ] },
{ "question": "How many sUAS may the remote PIC operate at a time?", 
  "answers": [ "5", 
               "1", 
               "No more than 2" ] },
{ "question": "“Unmanned aircraft” is defined as a device operated", 
  "answers": [ "during search and rescue operations other than the public", 
               "without the possibility of direct human intervention from within or on the aircraft", 
               "for hobby and recreational use when not certified" ] },
{ "question": "Under what conditions may objects be dropped from the sUAS?", 
  "answers": [ "if prior permission is received from the FAA", 
               "in an emergency", 
               "if precautions are taken to avoid injury or damage to persons or property on the surface" ] },
{ "question": "Unless otherwise authorized, what is the maximum airspeed at which a person may operate an sUAS below 400 feet?", 
  "answers": [ "80 mph", 
               "100 mph", 
               "200 knots" ] },
{ "question": "When an ATC clearance has been obtained, no remote PIC may deviate from that clearance, unless that pilot obtains an amended clearance. The one exception to this regulation is", 
  "answers": [ "an emergency", 
               "when the clearance states “at pilot’s discretion”", 
               "if the clearance contains a restriction" ] },
{ "question": "Under what conditions would a small unmanned aircraft not have to be registered before it is operated in the United States?", 
  "answers": [ "When the aircraft has a takeoff weight that is more than .55 pounds but less than 55 pounds, not including fuel and necessary attachments", 
               "When the aircraft weighs less than .55 pounds on take-off, including everything that is onboard or attached to the aircraft", 
               "All small unmanned aircraft need to be registered regardless of the weight of the aircraft before, during, or after the flight" ] },
{ "question": "According to 14 CFR Part 107, what is required to operate a small unmanned aircraft within 30 minutes after official sunset?", 
  "answers": [ "Use of a transponder", 
               "Must be operated in a rural area", 
               "Use of lighted anti-collision lights" ] },
{ "question": "Under what circumstances may lithium batteries be carried during a sUAS operations?", 
  "answers": [ "Lithium batteries may be carried only when installed as the primary power for the operation", 
               "Lithium batteries are prohibited from sUAS operations", 
               "Lithium batteries may be carried in a sealed storage container away from the sUAS fuel source" ] },
{ "question": "As a remote pilot with a sUAS rating, under which situation can you deviate from 14 CFR Part 107?", 
  "answers": [ "When conducting public operations during a search mission.", 
               "In response to an in-flight emergency.", 
               "Flying for enjoyment with family and friends." ] },
{ "question": "When requesting a waiver, the required documents should be presented to the FAA at least how many days prior to the planned operation?", 
  "answers": [ "90 days", 
               "30 days", 
               "10 days" ] },
{ "question": "While operating a small unmanned aircraft system (a sUAS), you experience a flyaway and several people suffer injuries. Which of the following injuries requires reporting to the FAA?", 
  "answers": [ "Scrapes and cuts bandaged on site", 
               "Minor bruises", 
               "An injury requiring an overnight hospital stay" ] },
{ "question": "After receiving a Part 107 remote pilot certificate with a sUAS rating, how often must you satisfy recurrent training requirements?", 
  "answers": [ "Every 6 months", 
               "Every 12 months", 
               "Every 24 months" ] },
{ "question": "A crew conducting surveillance anticipates losing visual line of sight with the sUAS within a small segment of the flight plan. The flight", 
  "answers": [ "may be conducted using binoculars", 
               "must be rerouted to maintain visual line of sight", 
               "may be conducted if the visual line of sight can be maintained for 50% of the route" ] },
{ "question": "Which of the following individuals may process an application for a Part 107 remote pilot certificate with a sUAS rating?", 
  "answers": [ "Commercial Balloon pilot", 
               "Designated Pilot examiner", 
               "Remote Pilot in command" ] },
{ "question": "Who holds the responsibility to ensure all crew members who are participating in the operation are not impaired by drugs or alcohol?", 
  "answers": [ "The FAA", 
               "Site supervisor", 
               "Remote Pilot in Command" ] },
{ "question": "According to 14 CFR Part 48, when must a person register a small UA with the Federal Aviation Administration?", 
  "answers": [ "When the small UA is used for any purpose other than as a model aircraft", 
               "Only when the operator will be paid for commercial services", 
               "All civilian small UAs weighing greater than 0.55 pounds must be registered regardless of its intended use" ] },
{ "question": "Which preflight action is specifically required of the pilot prior to each flight?", 
  "answers": [ "Check the aircraft logbooks for appropriate entries", 
               "Visually inspect the pilot certificates of all crew members", 
               "Assess the operating environment including local weather conditions, local airspace and any flight restrictions, the location of persons and property on the surface, and other ground hazards" ] },
{ "question": "Which is true regarding the presence of alcohol within the human body?", 
  "answers": [ "A small amount of alcohol increases vision acuity", 
               "Judgment and decision making abilities can be adversely affected by even small amounts of alcohol", 
               "An increase in altitude decreases the adverse effect of alcohol" ] },
{ "question": "What actions should pilots take if collision is anticipated?", 
  "answers": [ "The remote pilot should adjust the sUAS course.", 
               "The manned aircraft pilot should give way to the right.", 
               "Both pilots should give way to the right." ] },
{ "question": "Which of the following types of operations are excluded from the requirements in 14 CFR Part 107?", 
  "answers": [ "Model aircraft for hobby use", 
               "Quad copter capturing aerial imagery for crop monitoring", 
               "UAS used for motion picture filming" ] },
{ "question": "According to 14 CFR Part 48, when would a small unmanned aircraft owner not be permitted to register it?", 
  "answers": [ "All persons must register their small unmanned aircraft.", 
               "The owner is less than 13 years of age.", 
               "If the owner does not have a valid US driver's license." ] },
{ "question": "Each person who holds a pilot certificate, a US driver's license, or a medical certificate shall present it for inspection upon the request for the Administrator, the National Transportation Safety board, or any", 
  "answers": [ "authorized representative of the Department of State", 
               "federal, state, or local law enforcement officer", 
               "authorized Administrator of the Department of Transportation" ] },
{ "question": "A person without a Part 107 remote pilot certificate may operate a sUAS for commercial operations", 
  "answers": [ "under the direct supervision of a remote PIC", 
               "only when visual observers participate in the operation", 
               "alone, if operating during daylight hours" ] },
{ "question": "You plan to operate a 33 lbs a sUAS to capture aerial imagery over real estate for use in sales listings. What FAA regulation is this a sUAS operation subject to?", 
  "answers": [ "14 CFR Part 101", 
               "14 CFR Part 107", 
               "This operation is not subject to FAA regulations" ] },
{ "question": "According to 14 CFR Part 107, the responsibility to inspect the small unmanned aircraft system (a sUAS) to ensure it is in safe operating condition rests with the", 
  "answers": [ "Remote Pilot in Command", 
               "Owner of the a sUAS", 
               "Visual Observer" ] },
{ "question": "In accordance with 14 CFR Part 107, at what maximum altitude can you operate a sUAS when inspecting a tower with a top at 1,000 AGL at close proximity (within 100 feet)?", 
  "answers": [ "1,400 feet MSL", 
               "1,400 feet AGL", 
               "400 feet AGL" ] },
{ "question": "You wish to start a local delivery business using a sUAS to drop small packages at the front door of a customer. The customer's residence is not always within visual line-of-sight (VLOS) of the Remote PIC located at the delivery facility. Under which circumstances would this be authorized?", 
  "answers": [ "With a waiver from the FAA", 
               "By utilizing a vehicle to follow the sUAS while en-route to maintain VLOS", 
               "There is currently no way to do this in compliance with AC 107-2" ] },
{ "question": "What action, if any, is appropriate if the remote pilot deviates from Part 107 during an emergency?", 
  "answers": [ "Take no special action since you are pilot-in-command", 
               "File a report to the FAA Administrator, as soon as possible", 
               "File a detailed report to the FAA Administrator, upon request" ] },
{ "question": "You are part of a news crew, operating a sUAS to cover a breaking story. You experience a flyaway during landing. The unmanned aircraft strikes a vehicle, causing approximately $800 worth of damage.  When must you report the accident to the FAA?", 
  "answers": [ "Within 10 days", 
               "Anytime", 
               "Not to exceed 30 days" ] },
{ "question": "Under Title 14 of the Code of Federal Regulations, what is the maximum penalty for falsification, alteration or fraudulent reproduction of certificates, logbooks, reports, and records?", 
  "answers": [ "Ineligibility to receive a certificate or rating for one year", 
               "Suspension or revocation of any certificate held", 
               "Imprisonment for 1 year and a $5,000.00 fine" ] },
{ "question": "When must a current remote pilot certificate be in the pilot's personal possession or readily accessible in the aircraft?", 
  "answers": [ "Anytime when acting as pilot-in-command or as a required crew member", 
               "When acting as a crew chief during launch and recovery", 
               "Only when a payload is carried" ] },
{ "question": "If sunset is 2021 and the end of evening civil twilight is 2043, when must a remote pilot terminate the flight?", 
  "answers": [ "2021", 
               "2043", 
               "2121" ] },
{ "question": "To avoid a possible collision with a manned airplane, you estimate that your small unmanned aircraft climbed to an altitude greater than 600 feet AGL. To whom must you report the deviation?", 
  "answers": [ "Upon request of the Federal Aviation Administration", 
               "The National Transportation Safety Board", 
               "Air Traffic Control" ] },
{ "question": "To satisfy medical requirements, all sUAS crew members must", 
  "answers": [ "Hold a valid third-class medical certificate", 
               "Complete a physical with an Aviation Medical examiner", 
               "Be free of any physical or mental condition that would interfere with the safe operation of the small unmanned aircraft system" ] },
{ "question": "A law enforcement officer witnesses careless or reckless behavior while observing a sUAS operation and requests the operator to submit to a drug or alcohol test. What are the consequences if this request is denied?", 
  "answers": [ "The operator may have their remote pilot certificate with a sUAS rating suspended or revoked.", 
               "The operator may be denied an application for a remote pilot certificate for up to 30 days.", 
               "The operator may have to pay a fine but their remote pilot certificate will not be affected." ] },
{ "question": "No person may attempt to act as a crew member of a sUAS with", 
  "answers": [ "0.004 percent by weight or more alcohol in the blood", 
               "0.04 percent by weight or more alcohol in the blood", 
               "0.4 percent by weight or more alcohol in the blood" ] },
{ "question": "Which crew member must hold a remote pilot certificate with a sUAS rating?", 
  "answers": [ "Person manipulating the controls", 
               "Visual Observer", 
               "Remote pilot-in-command" ] },
{ "question": "What speed limit applies to a sUAS operation?", 
  "answers": [ "200 knots", 
               "80 mph", 
               "100 mph" ] },
{ "question": "Whose sole task during a sUAS operation is to watch the sUAS and report potential hazards to the rest of the crew?", 
  "answers": [ "Visual Observer", 
               "Remote pilot-in-command", 
               "Person manipulating the controls" ] },
{ "question": "According to 14 CFR Part 107, a sUAS is an unmanned aircraft system weighing", 
  "answers": [ "Less than 55 lbs.", 
               "55 kg or less", 
               "55 lbs. or less" ] },
{ "question": "Which of the following operations is compliant with 14 CFR Part 107?", 
  "answers": [ "Remote PIC is driving a moving vehicle while operating a sUAS in a sparsely populated area", 
               "Remote PIC is a passenger on an aircraft in flight while operating a sUAS", 
               "Remote PIC is a passenger on a moving boat while operating a sUAS in an unpopulated area" ] },
{ "question": "In accordance with 14 CFR Part 107, you may operate a sUAS from a moving vehicle when no property is carried for compensation or hire", 
  "answers": [ "Over a sparsely populated area", 
               "Over suburban areas", 
               "Over a parade or other social event" ] },
{ "question": "The FAA may approve your application for a waiver of provisions in Part 107 only when it has been determined that the proposed operation", 
  "answers": [ "Involves public aircraft or air carrier operations", 
               "Can be safely conducted under the terms of that certificate of waiver", 
               "Will be conducted outside the United States" ] },
{ "question": "Within how many days must a sUAS accident be reported to the FAA?", 
  "answers": [ "10 days", 
               "90 days", 
               "30 days" ] },
{ "question": "Which of the following operations would be regulated by 14 CFR Part 107?", 
  "answers": [ "Conducting public operations during a search mission.", 
               "Flying for enjoyment with family and friends.", 
               "Operating your sUAS for an imagery company." ] },
{ "question": "Which action is specifically required of the remote pilot prior to each flight?", 
  "answers": [ "Make a plan to keep non-participants clear, indoors, or under cover.", 
               "Check the aircraft logbooks to ensure maintenance is current.", 
               "Identify a non-participant who will be near the sUAS operation to help with and see and avoid procedures." ] },
{ "question": "Which of the following would medically disqualify a Remote pilot?", 
  "answers": [ "Taking a prescription medication that does not have any noticeable side effect", 
               "A migraine headache with the side effect of blurred vision", 
               "Occasional muscle soreness following exercise" ] },
{ "question": "What may be used to assist compliance with a sUAS see-and-avoid requirements?", 
  "answers": [ "Binoculars", 
               "Remote pilot diligence", 
               "First-person view camera" ] },
{ "question": "As you are flying your sUAS, valued at $1000, over a home to photograph it for real estate sales purposes, the sUAS has a failure causing it to fall onto an awning, causing some minor damage. The fair market value of the awning is $800 but it can be repaired for $400. What type of report is required?", 
  "answers": [ "No report is required.", 
               "A sUAS accident report to the FAA, within 10 days of operation.", 
               "A sUAS incident report to the FAA, within 10 days of the operation." ] },
{ "question": "Who is responsible for ensuring that there are enough crew members for a given sUAS operation?", 
  "answers": [ "Person manipulating the controls.", 
               "Visual Observer.", 
               "Remote Pilot in Command." ] },
{ "question": "If a certified pilot changes permanent mailing address and fails to notify the FAA Airmen Certification Branch of the new address, the pilot is entitled to exercise the privileges of the pilot certificate for a period of only", 
  "answers": [ "60 days after the move", 
               "30 days after the date of the move", 
               "90 days after the move" ] },
{ "question": "A person may not act as a crew member of the sUAS if alcoholic beverages have been consumed by that person within the preceding", 
  "answers": [ "8 hours", 
               "12 hours", 
               "24 hours" ] },
{ "question": "In accordance with 14 CFR Part 107, except when within a 400-foot radius of a structure, at what maximum altitude can you operate a sUAS?", 
  "answers": [ "600 feet AGL", 
               "400 feet AGL", 
               "500 feet AGL" ] },
{ "question": "Which crew member is required to be under the direct supervision of the remote PIC when operating a sUAS?", 
  "answers": [ "Remote pilot-in-command", 
               "Person manipulating the controls", 
               "Visual Observer" ] },
{ "question": "Which aircraft has right-of-way over other traffic?", 
  "answers": [ "A sUAS", 
               "A quad copter", 
               "An airplane" ] },
{ "question": "The basic weather minimums for operating a sUAS up to the 400 AGL limit are", 
  "answers": [ "900-foot ceiling and 3-mile visibility", 
               "2000-foot ceiling and 1-mile visibility", 
               "Clear of clouds and 2-mile visibility" ] },
{ "question": "You are operating a 1280 g (2.8 lb.) quad copter for your own enjoyment. What FAA regulation is this sUAS operation subject to?", 
  "answers": [ "14 CFR Part 107", 
               "This operation is not subject to FAA regulations", 
               "14 CFR Part 101" ] },
{ "question": "Except when necessary for takeoff or landing, what is the minimum safe altitude required for a remote pilot to operate a sUAS over people?", 
  "answers": [ "An altitude allowing, if a power unit fails, an emergency landing without undue hazard to person or property on the surface.", 
               "You may not operate a sUAS over people who are not part of the sUAS operation.", 
               "An altitude of 200 feet above the highest obstacle within a horizontal radius of 1000 feet." ] },
{ "question": "You have accepted football tickets in exchange for using your sUAS to videotape a future construction zone. What FAA regulation is this sUAS operation subject to?", 
  "answers": [ "14 CFR Part 107", 
               "14 CFR Part 101", 
               "This operation is not subject to FAA regulations" ] },
{ "question": "When using a small unmanned aircraft in a commercial operation, who is responsible for informing the participants about emergency procedures?", 
  "answers": [ "The lead visual observer", 
               "Remote Pilot in Command", 
               "The FAA inspection-in-charge" ] },
{ "question": "An autonomous operation requires the following crew members.", 
  "answers": [ "Remote PIC, Visual observer", 
               "Remote PIC", 
               "Remote Pilot, visual observer, person manipulating the controls" ] },
{ "question": "Power company employees use a sUAS to inspect a long stretch of high voltage power lines due to muddy conditions, their vehicle must stay beside the road and the crew must use binoculars to maintain visual line of sight with the aircraft. Is this a sUAS operation in compliance with 14 CFR Part 107?", 
  "answers": [ "No, the operation is not in compliance with Part 107.", 
               "Yes, the operation is in compliance with Part 107.", 
               "There is not enough information to make a determination." ] },
{ "question": "Who is ultimately responsible for preventing a hazardous situation before an accident occurs?", 
  "answers": [ "Person manipulating the controls", 
               "Visual Observer", 
               "Remote Pilot in Command" ] },
{ "question": "If you are caught smoking marijuana the FAA will", 
  "answers": [ "Send you to a drug treatment center", 
               "Issue an immediate suspension or revocation of your pilot certificate", 
               "Deny all future pilot applications" ] },
{ "question": "Sunrise is 0645. When can you launch your sUAS operation?", 
  "answers": [ "06:45", 
               "06:15", 
               "07:15" ] },
{ "question": "Which of these operations must comply with 14 CFR Part 107?", 
  "answers": [ "Civil operations", 
               "Civil and public operations", 
               "Public and military operations" ] },
{ "question": "If requested, to whom must I present my Remote Pilot Certificate?", 
  "answers": [ "A person of authority", 
               "FAA Inspector", 
               "An authorized representative of the Department of State" ] },
{ "question": "What FAA resource can pilots reference to learn more about the impact of drugs and alcohol on flight?", 
  "answers": [ "The Pilot's Handbook of Aeronautical Knowledge", 
               "The Pilot Operating Handbook", 
               "NOTAMs" ] },
{ "question": "When can someone with a marijuana conviction apply for a Remote Pilot certificate?", 
  "answers": [ "Never", 
               "18 months", 
               "1 year" ] },
{ "question": "During a flight of your small UA, you observe a hot air balloon entering the area. You should", 
  "answers": [ "Yield the right-of-way to the hot air balloon.", 
               "Ensure the UA passes below, above, or ahead of the balloon.", 
               "Expect the hot air balloon to climb above your altitude." ] },
{ "question": "According to 14 CFR Part 107, what is the maximum ground speed for a small UA?", 
  "answers": [ "87 knots", 
               "87 mph", 
               "100 knots" ] },
{ "question": "You plan to release golf balls from your small UA at an altitude of 100 feet AGL. You must ensure the objects being dropped will", 
  "answers": [ "not create an undue hazard to persons or property", 
               "land within 10 feet of the expected landing zone", 
               "not cause property damage in excess of $300" ] },
{ "question": "A small UA causes an accident and your crew member loses consciousness. When do you report the accident?", 
  "answers": [ "No accidents need to be reported", 
               "When requested by the UA owner", 
               "Within 10 days of the accident" ] },
{ "question": "(Refer to Figure) You have been contracted to inspect towers located approximately 4 NM south of the Sioux Gateway (SUX) airport operating an unmanned aircraft. What is the maximum altitude above ground level (AGL) that you are authorized to operate over the top of the towers?", 
  "figure" : "figure26.png",
  "answers": [ "400 feet AGL", 
               "402 feet AGL", 
               "802 feet AGL" ] },
{ "question": "Upon request by the FAA, the remote pilot-in-command must provide", 
  "answers": [ "a logbook documenting small UA landing currency", 
               "a remote pilot certificate with a small UAS rating", 
               "any employer issued photo identification" ] },
{ "question": "After having dinner and wine, your client asks you to go outside to demonstrate the small UA's capabilities. You must", 
  "answers": [ "pass a self-administered sobriety test before operating a small UA", 
               "not operate a small UA within 8 hours of consuming any alcoholic beverage", 
               "ensure that your visual observer has not consumed any alcoholic beverage in the previous 12 hours" ] },
{ "question": "A small UA must be operated in a manner which", 
  "answers": [ "does not endanger the life or property of another", 
               "requires more than one visual observer", 
               "never exceeds 200 feet AGL" ] },
{ "question": "The refusal of a remote PIC to submit to a blood-alcohol test when requested by a law enforcement officer", 
  "answers": [ "are grounds for suspension or revocation of their remote pilot certificate", 
               "can be delayed for a period up to 8 hours after the request", 
               "has no consequences to the remote pilot certificate " ] }
];

regsAbank = [
{ "correct": "A", 
    "explain": "You may operate a sUAS from a moving vehicle if you are in a sparsely populated area and the driver does not serve as the remote PIC, person manipulating the controls, or visual observer. Reference: 14 CFR 107.25" },
{ "correct": "C", 
    "explain": "You may not operate a small unmanned aircraft directly over another person unless that person is directly involved in the operation (such as a visual observer or other crew member) or within a safe cover, such as inside a stationary vehicle or a protective structure that would protect a person from harm if the small unmanned aircraft were to crash into that structure. Reference: 14 CFR 107.39" },
{ "correct": "C", 
    "explain": "This scenario is not compliant with Part 107. You may not operate over non-participants without safe cover and you may not drop objects in a manner that creates hazard." },
{ "correct": "A", 
    "explain": "A remote pilot-in-command must be used during Part 107 a sUAS operations. A visual observer is optional. The person manipulating the controls may be the remote PIC, or must be operating under the direct supervision of the remote PIC. Reference:14 CFR 107.19" },
{ "correct": "B", 
    "explain": "A person may not operate or act as a remote pilot-in-command or visual observer in the operation of more than one unmanned aircraft at the same time. " },
{ "correct": "B", 
    "explain": "An unmanned aircraft means an aircraft operated without the possibility of direct human intervention from within or on the aircraft. Reference: 14 CFR 107.1, 107.3, AC 107-2" },
{ "correct": "C", 
    "explain": "No items may be dropped from the small unmanned aircraft in a manner that creates undue hazard to persons or property. Reference: 14 CFR 107.23" },
{ "correct": "B", 
    "explain": "The sUAS cannot be flown faster than a ground speed of 87 knots (100mph) and must be operated below 400 feet. Reference: 14 CFR 107.51" },
{ "correct": "A", 
    "explain": "Except in an emergency, no person may operate an aircraft contrary to an ATC clearance or instruction. Reference: 14 CFR 107.21" },
{ "correct": "B", 
    "explain": "Owners must register the sUAS if it is greater than 0.55 lbs., less than 55 pounds and operated under the provisions of the 14 CFR Part 107. Reference: 14 CFR 107.13" },
{ "correct": "C", 
    "explain": "When a sUAS operations are conducted during civil twilight, the sUAS must be equipped with anti-collision lights that are capable of being visible for at least 3 statute miles. Reference: 14 CFR 107.29" },
{ "correct": "A", 
    "explain": "Lithium batteries that are installed in a sUAS for power during the operation are not considered a hazardous material under Part 107. However, spare (uninstalled) lithium batteries would meet the definition of hazardous material and may not be carried on the sUAS. Reference: AC 107-2" },
{ "correct": "B", 
    "explain": "In case of an in-flight emergency, the remote PIC is permitted to deviate from any rule of Part 107 to the extent necessary to respond to that emergency. Reference: 14 CFR 107.21" },
{ "correct": "A", 
    "explain": "Although not required by Part 107, the FAA encourages applicants to submit their application at least 90 days prior to the start of the proposed operation. The FAA will strive to complete review and adjudication of waiver within 90 days; however, the time required for the FAA to make a determination regarding waiver requests will vary based on the complexity of the request. Reference: AC 107-2" },
{ "correct": "C", 
    "explain": "The remote PIC must report any a sUAS accident to the FAA, within 10 days of the operation, if a serious injury to any person or any loss of consciousness occurs. It would be considered a serious injury if a person requires hospitalization. Reference: 14 CFR 107.9, AC 107-2" },
{ "correct": "C", 
    "explain": "Remote pilot certificate holders with a sUAS rating must meet the recurrent training requirements after 24 months. This retraining can be satisfied by completing the online FAA course or taking the FAA knowledge exam. Reference: 14 CFR Part 107.63 and 107.65; AC 107-2" },
{ "correct": "B", 
  "explain": "The sUAS must remain within visual line of sight (VLOS) of flight crew members. The VLOS requirement would not prohibit actions such as scanning the airspace or briefly looking down at the 219 Revised December 2022 sUAS control station. Should the remote PIC or person manipulating the controls lose VLOS of the small UA, he or she must regain VLOS as soon as possible. Reference: 14 CFR 107.31" },
{ "correct": "B", 
  "explain": "The remote pilot application must be submitted to a Flight Standards District Office (FSDO), a designated pilot examiner (DPE), an airman certification representative for a pilot school, a certified flight instructor (CFI), or other person authorized by the Administrator to process the application. Reference: 14 CFR 107.63 and 61.56" },
{ "correct": "C", 
  "explain": "The remote PIC or person manipulating the flight controls of a sUAS must comply with the \"do not operate while impaired\" regulations. Reference: 14 CFR 107.19 (b), 107.19(d) and 107.57" },
{ "correct": "C", 
  "explain": "Owners must register the sUAS if it is greater than 0.55 lbs., less than 55 pounds and operated under the provisions of the 14 CFR Part 107. Reference: 14 CFR 107.13" },
{ "correct": "C", 
  "explain": "Each remote pilot shall, before each flight, assess the operating environment including local weather condition, local airspace and any flight restrictions, the location of persons and property on the surface, and other ground hazards. Reference: 14 CFR 107.49" },
{ "correct": "B", 
  "explain": "As little as one ounce of liquor, one bottle of beer, or four ounces of wine can impair flying skills. Reference: AIM 8-1-1" },
{ "correct": "A", 
  "explain": "The remote PIC must be able to maneuver the sUAS to avoid a collision and prevent other aircraft from having to take evasive action. Reference: 14 CFR 107.37" },
{ "correct": "A", 
  "explain": "14 CFR Part 107 does not apply to model aircraft that meet the criteria in 14 CFR 101.41, amateur rockets, moored balloons or unmanned free balloons, kites, operations conducted outside the United States, public aircraft operations, and air carrier operations." },
{ "correct": "B", 
  "explain": "The sUAS must be registered by a person who is at least 13 years of age Reference: 14 CFR 107.13, 91.2013" },
{ "correct": "C", 
  "explain": "A remote pilot-in-command, owner, or person manipulating the flight controls of a small unmanned aircraft must, upon request, make available to the administrator: (1) the remote pilot certificate with a small UAS rating; and (2) any other document, record, or report required. Reference: 14 CFR 107.7" },
{ "correct": "A", 
  "explain": "A person who does not hold a remote pilot certificate or a remote pilot that has not met the recurrent testing/training requirements of part 107 may operate the sUAS under Part 107, as long as he or she is directly supervised by a remote PIC and the remote PIC has the ability to immediately take direct control of the a sUAS. Reference: 14 CFR 107.12" },
{ "correct": "B", 
  "explain": "This a sUAS operation is subject to 14 CFR part 107 because the aerial imagery is for the furtherance of a business, making it commercial in nature. Reference: 14 CFR 107.3" },
{ "correct": "A", 
  "explain": "The remote PIC must complete a preflight familiarization, inspection, and other actions, such as crew member briefings, prior to beginning flight operations. Reference: 14 CFR 107.49" },
{ "correct": "B", 
  "explain": "The sUAS cannot be flown higher than 400 feet AGL unless flown within a 400-foot radius of a structure and is not flown higher than 400 feet above the structure's immediate upper-most limit. Reference: 14 CFR 107.51" },
{ "correct": "C", 
  "explain": "The FAA has stated that they will not provide waivers for beyond VLOS during the carriage of goods for hire. Also, moving vehicles (land or sea) are not authorized to be used during flights upon which goods are carried for hire. Reference: AC 107-2" },
{ "correct": "C", 
  "explain": "Each remote PIC who deviates from a rule in Part 107 must, upon request of the FAA administrator, send a written report of that deviation to the Administrator Reference: 14 CFR 107.21" },
{ "correct": "A", 
  "explain": "Report any a sUAS accident to the FAA within 10 days if it results in serious injury, loss of consciousness, or repairs costing over $500. Reference: 14 CFR 107.9" },
{ "correct": "B", 
  "explain": "14 CFR 65.20 states that any person who falsifies or makes a fraudulent entry in a logbook, report or record is subject to the suspension or revocation of any airman or ground instructor certificate or rating held by that person. Reference: 14 CFR 107.6" },
{ "correct": "A", 
  "explain": "No person may act as a pilot-in-command (PIC), or in any other capacity as a required pilot flight crew member when operating a sUAS unless he or she has in possession or readily accessible a current-pilot certificate. Reference: 14 CFR 107.7" },
{ "correct": "B", 
  "explain": "A remote pilot may not act as pilot-in-command of a sUAS at night. A remote pilot must land by the end of evening twilight. Reference: 14 CFR 107.29" },
{ "correct": "A", 
  "explain": "Each remote PIC who deviates from a rule in Part 107 must, upon request of the FAA administrator, send a written report of that deviation to the Administrator. Reference: 14 CFR 107.21" },
{ "correct": "C", 
  "explain": "No person may manipulate the flight controls of a small unmanned aircraft system or act as a remote pilot-in-command, visual observer, or direct participant in the operation of the small unmanned aircraft if he or she knows or has reason to know that he or she has a physical or mental condition that would interfere with the safe operation of the small unmanned aircraft system. Reference: 14 CFR 107.17" },
{ "correct": "A", 
  "explain": "A refusal to submit to a test to indicate the percentage by weight of alcohol in the blood, when requested by a law enforcement officer, or a refusal to furnish or authorize the release of the test results requested by the Administrator, is grounds for denial of an application for a remote pilot certificate with a small UAS rating for a period of up to 1 year after the date of that refusal; or suspension or revocation of a remote pilot certificate with a small UAS rating. Reference: 14 CFR 107.59" },
{ "correct": "B", 
  "explain": "No person may act, or attempt to act, as a crew member of a civil aircraft while having .04 percent or more, by weight alcohol in the blood. Reference: 14 CFR 107.27, 91.17" },
{ "correct": "C", 
  "explain": "The remote PIC must hold a Part 107 remote pilot certificate with a sUAS rating before conducting any a sUAS operation. Reference: 14 CFR 107.12" },
{ "correct": "C", 
  "explain": "The sUAS cannot be flown faster than a ground speed of 87 knots (100mph). Reference: 14 CFR 107.51" },
{ "correct": "A", 
  "explain": "The visual observer (when asked by the remote PIC) maintains visual line of sight with a sUAS and reports any potential hazards to the remote PIC and person manipulating the controls. Reference: 14 CFR 107.33" },
{ "correct": "A", 
  "explain": "Small unmanned aircraft (a sUAS) means an unmanned aircraft weighing less than 55 pounds on takeoff, including everything that is on board or otherwise attached to the aircraft. Reference: 14 CFR 107.1, AC 107-2" },
{ "correct": "C", 
  "explain": "Operation of a sUAS is permitted from a moving land or waterborne vehicle over a sparsely populated (or unpopulated) area. Reference: 14 CFR 107.25" },
{ "correct": "A", 
  "explain": "Operation of a sUAS is permitted from a moving land or waterborne vehicle over a sparsely populated (or unpopulated) area. Reference: 14 CFR 107.25" },
{ "correct": "B", 
  "explain": "If the remote PIC determines that the operation cannot be conducted within the regulatory structure of Part 107, he or she is responsible for applying for a Certificate of Waiver (COW) and proposing a safe alternative to the operation. This COW will allow a sUAS operation to deviate from certain provisions to Part 107 as long as the FAA finds that the proposed operation can be safely conducted under the terms of that Certificate of Waiver. Reference: 14 CFR 107.200" },
{ "correct": "A", 
  "explain": "Report any a sUAS accident to the FAA within 10 days if it results in serious injury, loss of consciousness, or repairs costing over $500. Reference: 14 CFR 107.9" },
{ "correct": "C", 
  "explain": "Part 107 regulates commercial a sUAS operations. Reference: 14 CFR 107.41 and 107.1" },
{ "correct": "A", 
  "explain": "You may not operate a small unmanned aircraft directly over another person unless that person is directly involved in the operation (such as a visual observer or other crew member) or within a safe cover, such as inside a stationary vehicle or a protective structure that would protect a person from harm if the small unmanned aircraft were to crash into that structure. Reference: 14 CFR 107.39" },
{ "correct": "B", 
  "explain": "No person may manipulate the flight controls of a small unmanned aircraft system or act as a remote pilot-in-command, visual observer, or direct participant in the operation of the small unmanned aircraft if he or she knows or has reason to know that he or she has a physical or mental condition that would interfere with the safe operation of the small unmanned aircraft system. Reference: 14 CFR 107.17" },
{ "correct": "B", 
  "explain": "The remote PIC also has a responsibility to remain clear of and yield right of way to all other aircraft, manned or unmanned, and avoid other potential hazards that may affect the remote PIC's operation of the aircraft. Reference: 14 CFR 107.37" },
{ "correct": "A", 
  "explain": "No report is required because the damage can be repaired for less than $500. A report is required only when damage to any property, other than the small UA, is greater than $500 to repair or replace the property (whichever is lower). The cost of the sUAS is not considered when determining if an event is considered to be an accident or incident. Reference: 14 CFR 107.9, AC 107-2" },
{ "correct": "C", 
  "explain": "The remote PIC is ultimately responsible for assessing the needs of the operation and preparing sufficient support crew members to ensure the safety of the operation. Reference: 14 CFR 107.12" },
{ "correct": "B", 
  "explain": "The holder of a remote pilot certificate who has made a change in his or her permanent mailing address may not, after 30 days from the date moved, exercise the privileges of his or her certificate unless he or she has notified in writing the FAA Airmen Certificate Branch Reference: 14 CFR 107.77" },
{ "correct": "A", 
  "explain": "No person may act or attempt to act as a crew member of a sUAS within 8 hours after the consumption of any alcoholic beverage. Remember \"8 hours bottle to throttle\" Reference: 14 CFR 107.27, 91.17" },
{ "correct": "B", 
  "explain": "The sUAS cannot be flown higher than 400 feet AGL unless flown within a 400-foot radius of a structure and is not flown higher than 400 feet above the structure's immediate upper-most limit. Reference: 14 CFR 107.51" },
{ "correct": "B", 
  "explain": "A non-certified person may manipulate the controls of the sUAS only if he or she is under the direct supervision of the remote PIC. Reference: 14 CFR 107.12" },
{ "correct": "C", 
  "explain": "The remote pilot operating a sUAS must yield right-of-way to all other manned aircraft, including aircraft operating on the surface of the aircraft. Reference: 14 CFR 107.37" },
{ "correct": "A", 
  "explain": "Part 107 a sUAS operations require minimum visibility of 3 SM and the minim distance from clouds must be no less than 500 feet below the cloud and 2000 feet horizontally from the cloud. To maintain 500 feet below the cloud, you must have a 900 foot ceiling to be able to operate to the maximum 400 AGL, or a ceiling that would allow the sUAS to operate at a lower AGL altitude. Reference: 14 CFR 107.51" },
{ "correct": "B", 
  "explain": "This a sUAS operation is not subject to FAA sUAS regulations because the sUAS operation is recreational in nature. Part 101 details the regulations pertinent to model aircraft and hobby operations. Reference: 14 CFR Part 107.3" },
{ "correct": "B", 
  "explain": "You may not operate a small unmanned aircraft directly over another person unless that person is directly involved in the operation (such as a visual observer or other crew member) or within a safe cover, such as inside a stationary vehicle or a protective structure that would protect a person from harm if the small unmanned aircraft were to crash into that structure. Reference: 14 CFR 107.39" },
{ "correct": "A", 
  "explain": "This a sUAS operation is subject to 14 CFR Part 107 because the compensation (money or otherwise) makes the operation commercial in nature Reference: 14 CFR 107.3" },
{ "correct": "B", 
  "explain": "Prior to flight, the remote PIC must ensure that all persons directly participating in the small unmanned aircraft operation are informed about the operating conditions, emergency procedures, contingency procedures, roles and responsibilities, and potential hazards. Reference: 14 CFR 107.49, AC 107-2" },
{ "correct": "B", 
  "explain": "An autonomous operation does not negate the requirement for a remote PIC. An autonomous operation is generally considered an operation in which the remote pilot inputs a flight plan into the CS, which sends it to the autopilot on the small UA. Reference: AC 107-2" },
{ "correct": "A", 
  "explain": "This scenario is not compliant with Part 107. Visual aids such as binoculars may be used only momentarily to enhance situational awareness. They may not be used during the duration of the operation. Reference: 14 CFR 107.31" },
{ "correct": "C", 
  "explain": "The remote PIC is ultimately responsible for assessing the needs of the operation and preparing sufficient support crew members to ensure the safety of the operation. Reference: 14 CFR 107.12" },
{ "correct": "B", 
  "explain": "A conviction for the violation of any Federal or State statute relating to the growing, processing, manufacture, sale, disposition, possession, transportation, or importation of narcotic drugs, marijuana, or depressant or stimulant drugs or substances is grounds for suspension or revocation of a remote pilot certificate with a small UAS rating. Reference: 14 CFR 107.57" },
{ "correct": "B", 
  "explain": "A remote pilot may not act as pilot-in-command of a sUAS at night. Night is defined as the time between the end of evening civil twilight and the beginning of morning civil twilight. Morning civil twilight is the period 30 minutes prior to sunrise until sunrise. This means you can launch your sUAS operation 30 minutes prior to sunrise. Reference: 14 CFR 107.29" },
{ "correct": "A", 
  "explain": "Part 107 addresses a sUAS operations of certain civil small unmanned aircraft within the National Airspace System. Reference: 14 CFR Part 107" },
{ "correct": "B", 
  "explain": "A remote pilot-in-command, owner, or person manipulating the flight controls of a small unmanned aircraft system must, upon request, make available to the Administrator: (1) the remote pilot certificate with a small UAS rating; and (2) any other document, record, or report required. Reference: 14 CFR 107.7" },
{ "correct": "A", 
  "explain": "The Pilot's Handbook of Aeronautical Knowledge (FAA-H-8083-25) provide information on the physiological effects of alcohol, prescription drugs, and over-the-counter medications. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "A conviction for the violation of any Federal or State statute relating to the growing, processing, manufacture, sale, disposition, possession, transportation, or importation of narcotic drugs, marijuana, or depressant or stimulant drugs or substances is grounds for denial of an application for a remote pilot certificate with a small UAS rating for a period of up to 1 year after the date of that act. Reference: 14 CFR 107.57" },
{ "correct": "A", 
  "explain": "The remote pilot operating a sUAS must yield right-of-way to all other manned aircraft, including aircraft operating on the surface of the airport. Reference: 14 CFR 107.37" },
{ "correct": "A", 
  "explain": "The sUAS cannot be flown faster than a ground speed of 87 knots (100 miles per hour) and must be operated below 400 feet. Reference: 14 CFR 107.51" },
{ "correct": "A", 
  "explain": "No items may be dropped from the small unmanned aircraft in a manner that creates undue hazard to persons or property. Reference: 14 CFR 107.23" },
{ "correct": "C", 
  "explain": "Report any a sUAS accident to the FAA within 10 days if it results in serious injury, loss of consciousness, or repairs costing over $500. Reference: 14 CFR 107.9" },
{ "correct": "C", 
  "explain": "The sUAS cannot be flown higher than 400 feet AGL unless flown within a 400-foot radius of a structure and no higher than 400 feet above the structure's immediate uppermost limit. One of the tower sets south of the SUX airport shows a tower at 402 feet AGL; you may operate over the top of these towers no higher than 802 feet AGL. Reference: 14 CFR 107.51 and Sectional Chart Legend" },
{ "correct": "B", 
  "explain": "A remote pilot-in-command, owner, or person manipulating the flight controls of a small unmanned aircraft system must, upon request, make available to the Administrator: (1) the remote pilot certificate with a small UAS rating; and (2) any other document, record, or report required. Reference: 14 CFR 107.7" },
{ "correct": "B", 
  "explain": "No person may act or attempt to act as a crew member of a sUAS within 8 hours after the consumption of any alcoholic beverage. Remember \"8 hours bottle to throttle.\" Reference: 14 CFR 107.17 and 91.17" },
{ "correct": "A", 
  "explain": "No person may continue flight of a small unmanned aircraft when he or she knows or has reason to know that the small unmanned aircraft system is no longer in a condition for safe operation. Reference: 14 CFR 107.15" },
{ "correct": "A", 
  "explain": "A refusal to submit to a test to indicate the percentage by weight of alcohol in the blood, when requested by a law enforcement officer, or a refusal to furnish or authorize the release of the test results requested by the Administrator, is grounds for denial of an application for a remote pilot certificate with a small UAS rating for a period of up to 1 year after the date of that refusal; or suspension or revocation of a remote pilot certificate with a small UAS rating. Reference: 14 CFR 107.59       " },
];