wxQbank = [
{ "question": "The presence of ice pellets at the surface is evidence that there", 
  "answers": [ "are thunderstorms in the area", 
               "is a temperature inversion with freezing rain at a higher altitude", 
               "has been a cold frontal passage" ] },
{ "question": "The minimum distance from clouds required for sUAS part 107 operations is", 
  "answers": [ "500 feet below, 2,000 feet horizontally", 
               "clear of clouds", 
               "500 feet above, 1,000 feet horizontally" ] },
{ "question": "What is the best way for a remote pilot to determine the likelihood of local fog formation?", 
  "answers": [ "Monitor the wind conditions to ensure the wind speed is not increasing", 
               "Monitor the barometric pressure to ensure that it is not decreasing", 
               "Monitor the temperature/dew point spread" ] },
{ "question": "Which weather phenomenon is always associated with a thunderstorm?", 
  "answers": [ "Heavy rain", 
               "Hail", 
               "Lightning" ] },
{ "question": "What effect does high-density altitude have on the efficiency of a UA propeller?", 
  "answers": [ "Density altitude does not affect propeller efficiency", 
               "Propeller efficiency is increased", 
               "Propeller efficiency is decreased" ] },
{ "question": "What are the characteristics of a moist, unstable air mass?", 
  "answers": [ "Turbulence and showery precipitation", 
               "Poor visibility and smooth air", 
               "Haze and smoke" ] },
{ "question": "In which environment is aircraft structural ice most likely to have the accumulation rate?", 
  "answers": [ "Cumulus clouds with below-freezing temperatures", 
               "Freezing rain", 
               "Freezing drizzle" ] },
{ "question": "One weather phenomenon that will always occur when flying across a front is a change in", 
  "answers": [ "wind direction", 
               "type of precipitation", 
               "stability of the air mass" ] },
{ "question": "A stable air mass is most likely to have which characteristic?", 
  "answers": [ "Showery precipitation", 
               "Poor surface visibility", 
               "Turbulent air" ] },
{ "question": "What is the expected duration of an individual microburst?", 
  "answers": [ "Two minutes with maximum winds lasting approximately 1 minute", 
               "One microburst may continue for as long as 2 to 4 hours", 
               "Seldom longer than 15 minutes from the time the burst strikes the ground until dissipation" ] },
{ "question": "(Refer to Figure) Between 1000Z and 1200Z the visibility at KMEM is forecast to be", 
  "figure": "wx-q11.png",
  "answers": [ "3 statute miles", 
               "1/2 statute mile", 
               "6 statute miles" ] },
{ "question": "(Refer to Figure) In the TAF for KMEM, what does \"SHRA\" stand for?", 
  "figure": "wx-q11.png",
  "answers": [ "A significant change in precipitation is possible", 
               "A shift in wind direction is expected", 
               "Rain Showers" ] },
{ "question": "What minimum visibility is required for a sUAS operation?", 
  "answers": [ "4 miles", 
               "1 mile", 
               "3 miles" ] },
{ "question": "(Refer to Figure) What is the forecast wind for KMEM from 1600Z until the end of the forecast?", 
  "figure": "wx-q11.png",
  "answers": [ "No significant wind", 
               "Variable in direction at 6 knots", 
               "Variable in direction at 4 knots" ] },
{ "question": "What measurement can be used to determine the stability of the atmosphere?", 
  "answers": [ "Actual lapse rate", 
               "Atmospheric pressure", 
               "Surface temperature" ] },
{ "question": "Which factor would tend to increase the density altitude at a given airport referenced in the weather briefing? ", 
  "answers": [ "An increase in barometric pressure", 
               "An increase in ambient temperature", 
               "A decrease in relative humidity" ] },
{ "question": "Low-level turbulence can occur and icing can become hazardous in which type of fog?", 
  "answers": [ "Rain-induced fog", 
               "Steam fog", 
               "Upslope Fog" ] },
{ "question": "(Refer to Figure) The wind direction and velocity at KJFK is from:", 
  "figure": "wx-q18.png",
  "answers": [ "180 degrees true at 4 knots", 
               "180 degrees magnetic at 4 knots", 
               "040 degrees true at 18 knots." ] },
{ "question": "During the life cycle of a thunderstorm, which stage is characterized predominately by downdrafts?", 
  "answers": [ "Cumulus", 
               "Dissipating", 
               "Mature" ] },
{ "question": "A strong steady wind exists out of the north. You need to photograph an area to the south of your location. You are located in an open field with no obstructions. Which of the following is not a concern during this operation?", 
  "answers": [ "Turbulent conditions will likely be a significant factor during the operation.", 
               "Strong wind conditions may consume more battery power at a faster rate than in calm Conditions.", 
               "Strong wind may exceed the performance of the sUAS making it impossible to recover." ] },
{ "question": "What situation is most conducive to the formation of radiation fog?", 
  "answers": [ "Moist, tropical air moving over cold offshore water", 
               "The movement of cold air over much warmer water", 
               "Warm, moist air over low, flatland areas on clear, calm nights" ] },
{ "question": "What causes variations in altimeter settings between weather reporting points?", 
  "answers": [ "Unequal heating of the Earth's surface", 
               "Variation of terrain elevation", 
               "Coriolis force" ] },
{ "question": "Thunderstorms which generally produce the most intense hazard to aircraft are", 
  "answers": [ "Steady-state thunderstorms", 
               "warm front thunderstorms", 
               "squall line thunderstorms" ] },
{ "question": "What conditions are necessary for the formation of thunderstorms?", 
  "answers": [ "High humidity, lifting force, and unstable conditions", 
               "High humidity, high temperature, and cumulus clouds", 
               "Lifting force, moist air, and extensive cloud cover" ] },
{ "question": "What feature is normally associated with the cumulus stage of a thunderstorm?", 
  "answers": [ "Roll cloud", 
               "Continuous updraft", 
               "Frequent lightning" ] },
{ "question": "Which of the following considerations is most relevant to a remote PIC when evaluating unmanned aircraft performance?", 
  "answers": [ "The number of available ground crew", 
               "The type of sUAS operation", 
               "Current weather conditions" ] },
{ "question": "What types of fog depend upon wind in order to exist?", 
  "answers": [ "Radiation fog and ice fog", 
               "Steam fog and ground fog", 
               "Advection fog and upslope fog" ] },
{ "question": "Thunderstorms reach their greatest intensity during the", 
  "answers": [ "mature stage", 
               "downdraft stage", 
               "cumulus stage" ] },
{ "question": "A non-frontal, narrow band of active thunderstorms that often develop ahead of a cold front is known as", 
  "answers": [ "squall line", 
               "prefrontal system", 
               "dry line" ] },
{ "question": "One in-flight condition necessary for structural icing to form is", 
  "answers": [ "small temperature dew point spread", 
               "visible moisture", 
               "stratiform clouds" ] },
{ "question": "If the outside air temperature (OAT) at a given altitude is warmer than standard, the density altitude is", 
  "answers": [ "higher than pressure altitude", 
               "equal to pressure altitude", 
               "lower than pressure altitude" ] },
{ "question": "Upon your preflight evaluation of weather, the forecasts you reference state there is an unstable air mass approaching your location. Which would not be a concern for your impending operation?", 
  "answers": [ "Thunderstorms", 
               "Turbulent conditions", 
               "Stratiform clouds" ] },
{ "question": "(Refer to Figure) Over which area should a remote pilot expect to find the highest amount of thermal currents under normal conditions?", 
  "figure": "figure20.png",
  "answers": [ "2",
               "7", 
               "5" ] },
{ "question": "(Refer to Figure) According to the KMEM forecast, what is the earliest time on the 12th (today) at which the visibility may be reduced below the 3SM minimum for a sUAS operations?", 
  "figure": "wx-q34.png",
  "answers": [ "2000Z",
               "1720Z", 
               "2200Z" ] },
{ "question": "The development of thermals depends upon", 
  "answers": [ "a counterclockwise circulation of air", 
               "temperature inversions", 
               "solar heating" ] },
{ "question": "What are the characteristics of stable air?", 
  "answers": [ "Good visibility and steady precipitation", 
               "Poor visibility and steady precipitation", 
               "Poor visibility and intermittent precipitation" ] },
{ "question": "While operating around buildings, the remote PIC should be aware of the creation of wind gusts that", 
  "answers": [ "enhance stability and imagery", 
               "change rapidly in direction and speed causing turbulence", 
               "increases the performance of the aircraft" ] },
{ "question": "An air mass moving inland from the coast in winter is likely to result in", 
  "answers": [ "fog", 
               "rain", 
               "frost" ] },
{ "question": "In which situation is advection fog most likely to form?", 
  "answers": [ "A warm, moist air mass on the windward side of mountains", 
               "An air mass moving inland from the coast in winter", 
               "A light breeze blowing colder air out to sea" ] },
{ "question": "If there is thunderstorm activity in the vicinity of an airport at which you plan to land, which hazardous atmospheric phenomenon might be expected during the recovery//landing of a sUAS?", 
  "answers": [ "Wind-shear turbulence", 
               "Precipitation static", 
               "Steady Rain" ] },
{ "question": "Which weather phenomenon signals the beginning of the mature stage of a thunderstorm?", 
  "answers": [ "the appearance of an anvil top", 
               "maximum growth rate of the clouds", 
               "precipitation beginning to fall" ] },
{ "question": "What are the standard temperatures and pressure values for sea level?", 
  "answers": [ "59 degrees C and 1013.2 millibars", 
               "59 degrees C and 29.92 millibars", 
               "15 degrees C and 29.92 Hg" ] },
{ "question": "(Refer to Figure) What are the current conditions for Chicago Midway Airport (KMDW)?", 
  "figure": "wx-q43.png",
  "answers": [ "Sky 700 feet overcast, visibility 1-1/2 SM, rain", 
               "Sky 7,000 feet overcast, visibility 1-1/2 SM, heavy rain", 
               "Sky 700 feet overcast, visibility 11, occasionally 2 SM, with rain" ] },
{ "question": "To get a complete weather overview for the planned flight, the remote pilot in command should obtain", 
  "answers": [ "An outlook briefing", 
               "A standard briefing", 
               "An abbreviated briefing" ] },
{ "question": "What would decrease the stability of an air mass?", 
  "answers": [ "Warming from below", 
               "Cooling from below", 
               "Decrease in water vapor" ] },
{ "question": "One of the most easily recognized discontinuities across a front is", 
  "answers": [ "a change in temperature", 
               "an increase in cloud coverage", 
               "an increase in relative humidity" ] },
{ "question": "Which statement is true concerning ASOS/AWOS weather reporting systems?", 
  "answers": [ "Each AWOS station is part of nationwide weather reporting stations.", 
               "ASOS locations perform weather observing functions necessary to generate METAR reports.", 
               "Both ASOS and AWOS have the capability of reporting density altitude, as long as it exceeds the airport elevation by more than 1,000 feet." ] },
{ "question": "Which is considered to be the most hazardous condition when flying a sUAS in the vicinity of thunderstorms?", 
  "answers": [ "Static electricity", 
               "Lightning", 
               "Wind shear and turbulence" ] },
{ "question": "How would high-density altitude affect the performance of a small unmanned aircraft?", 
  "answers": [ "No change in performance", 
               "Increased performance", 
               "Decreased performance" ] },
{ "question": "Which type of weather phenomenon that may concern a remote pilot is common among cold fronts?", 
  "answers": [ "Thunderstorms and heavy rain", 
               "Long term periods of reduced visibility", 
               "Long periods of steady precipitation" ] },
{ "question": "Every physical process of weather is accompanied by or is the result of a", 
  "answers": [ "movement of air", 
               "pressure differential", 
               "Heat exchange" ] },
{ "question": "In what stage are thunderstorms the strongest?", 
  "answers": [ "Raining", 
               "Dissipating", 
               "Building" ] },
{ "question": "(Refer to Figure) What is the minimum base of the cloud layer to fly to the top of the towers 4 NM east of Onawa?", 
  "figure": "wx-q53.png",
  "answers": [ "792 feet AGL", 
               "292 feet AGL", 
               "1,335 feet MSL" ] },
{ "question": "A non-frontal, narrow band of active thunderstorms that often develop ahead of a cold front is known as a", 
  "answers": [ "prefrontal system", 
               "squall line", 
               "dry line" ] },
{ "question": "(Refer to Figure) What are the VFR minimum visibility requirements over Plantation Airport?", 
  "figure": "wx-q55.png",
  "answers": [ "1 SM", 
               "5 SM", 
               "3 SM" ] },
{ "question": "Where are squalls most likely to form?", 
  "answers": [ "High altitude", 
               "Low altitude", 
               "At any altitude" ] },
{ "question": "What will a convective SIGMET be issued for?", 
  "answers": [ "Squall line thunderstorms", 
               "Visibility less than 3 miles", 
               "Surface winds greater than 40 knots" ] },
{ "question": "What effect does humidity have on performance?",
  "answers": [ "It has no effect on performance", 
               "It increases performance", 
               "It decreases performance" ] },
{ "question": "Clouds, fog, or dew will always form when", 
  "answers": [ "water vapor condenses", 
               "water vapor is present", 
               "relative humidity reaches 100 percent" ] },
{ "question": "What weather provides the best flying conditions?", 
  "answers": [ "Warm, moist air", 
               "Cool, dry air", 
               "Turbulence" ] },
{ "question": "(Refer to Figure) You are inspecting the lighted towers approximately 8 NM SW of the Corpus Christi Intl Airport (CRP). What is the lowest cloud cover that will enable you to inspect the top of the tower?", 
  "figure": "wx-q61.png", 
  "answers": [ "1,104 feet MSL", 
               "1,604 feet MSL", 
               "1,054 feet MSL" ] },
{ "question": "You have received an outlook briefing from flight service through 1800wxbrief.com. The briefing indicates you can expect a low-level temperature inversion with high relative humidity. What weather conditions would you expect?", 
  "answers": [ "Smooth air, poor visibility, fog, haze, or low clouds", 
               "Light wind shear, poor visibility, haze, and light rain", 
               "Turbulent air, poor visibility, fog, low stratus type clouds, and showery precipitation" ] },
{ "question": "(Refer to Figure) The remarks section for KMDW has \"RAB35\" listed. This entry means", 
  "figure": "wx-q61.png", 
  "answers": [ "blowing mist has reduced the visibility to 1-1/2 SM", 
               "rain began at 1835Z", 
               "the barometer has risen .35\" Hg" ] },
{ "question": "Wind shear can exist", 
  "answers": [ "at all altitudes", 
               "at low altitudes", 
               "at high altitudes" ] },
{ "question": "What environment is most conducive to frost formation?", 
  "answers": [ "Dew point of the surface is below freezing, dew point is above freezing", 
               "Surface temperature is below freezing, air temperature is below freezing", 
               "Surface temperature above is freezing, air temperature is below freezing" ] },
{ "question": "The weather report lists the ceiling at 800 feet. What is the highest you can operate your sUAS?", 
  "answers": [ "200 feet AGL", 
               "800 feet AGL", 
               "300 feet AGL" ] },
{ "question": "The zone between different temperature, humidity, and wind is called", 
  "answers": [ "A front", 
               "An air mass", 
               "Wind shear" ] }
];

wxAbank = [
{ "correct": "B", 
  "explain": "Ice pellets always indicate freezing rain at higher altitude Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Part 107 a sUAS operations require the minimum distance of the small unmanned aircraft from clouds must be no less than 500 feet below the cloud and 2,000 feet horizontally from the cloud. Reference: 14 CFR 107.51" },
{ "correct": "C", 
  "explain": "Fog is more likely to form when the temperature and dew point convergence. A difference between these two temperatures of 3 degrees C (or 5 degrees F) is indicative of possible fog formation. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "A thunderstorm is, in general, a local storm invariably produced by a cumulonimbus cloud, and is always accompanied by lightning and thunder. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "The propeller produces thrust in proportion to the mass of air being accelerated through the rotating blades. If the air is less dense, propeller efficiency is decreased. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Characteristics of a moist unstable air mass include cumuliform clouds, showery precipitation, rough air (turbulence), and good visibility (except in blowing obstructions) Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "A condition favorable for rapid accumulation of clear icing is freezing rain below a frontal surface. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Wind direction always changes across a front Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Characteristics of a stable air mass include stratiform clouds and fog, continuous precipitation, smooth air, and fair to poor visibility in haze and smoke. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "An individual microburst will seldom last longer than 15 minutes from the time it strikes the ground until dissipation. However, there may be multiple microbursts in the area. Reference: AIM 7-1-25" },
{ "correct": "A", 
  "explain": "Between 1000Z and 1200Z, the visibility at KMEM is forecast to be 3 statute miles (BECMG 1012... 3SM) Reference: AC 00-45" },
{ "correct": "C", 
  "explain": "\"SH\" stands for showers and \"RA\" stands for rain. Reference: AC 00-45" },
{ "correct": "C", 
  "explain": "Crew members must operate a sUAS Part 107 operations with a minimum visibility, as observed from the location of the control station, no less than 3 statute miles. Reference: 14 CFR 107.51" },
{ "correct": "B", 
  "explain": "From 1600Z until the end of the forecast, wind will be variable in direction at 6 knots (VRB06KT) Reference: AC 00-45" },
{ "correct": "A", 
  "explain": " The difference between the existing lapse rate of a given mass of air and the adiabatic rates of cooling in upward moving air determines if the air is stable or unstable. Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "On a hot day, the air becomes \"thinner\" or lighter, and its density is equivalent to a higher altitude in the standard atmosphere, thus the term \"high density altitude\" Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Steam fog forms in the winter when cold, dry air passes from land areas over comparatively warm ocean waters. Low level turbulence can occur and icing can become hazardous in a steam fog. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "The wind is reported as a five digit group (six digits if speed is over 99 knots). The first three digits is the direction the wind is blowing from rounded to the nearest tens of degrees relative to true (not magnetic) north, or \"VRB\" if the direction is variable. The next two digits is the speed in knots or if over 99 knots, the next three digits. If the wind is gusty, it is reported as a \"G\" after the speed followed by the highest gust reported. The abbreviation \"KT\" is appended to denote the use of knots for wind speed. The wind group for KJFK is 18004KT which means the wind from 180 degrees at 4 knots. Reference: AC 00-45" },
{ "correct": "B", 
  "explain": "Downdrafts characterize the dissipating stage of the thunderstorm cell and the storm dies rapidly. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Unmanned aircraft often have limited performance and therefore in high wind conditions, it may consume more power to maintain position or other maneuvers than in calm air. If the wind is strong enough, the sUAS's performance might not be able to adequately counter the wind, making it impossible to fly back to you for recovery. Reference: FAA-H-8083-25, 14 CFR Part 107.49" },
{ "correct": "C", 
  "explain": "Conditions favorable for radiation fog are clear sky, little or no wind, and small temperature/ dew point spread (high relative humidity). Radiation fog is restricted to land because water surfaces cool little from nighttime radiation. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "All altimeter settings are corrected to sea level, unequal heating of the Earth's surface causes pressure differences. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "A squall line is a non-frontal, narrow band of active thunderstorms. The line may be too long to easily detour and too wide and severe to penetrate. It often contains severe steady state thunderstorms and presents the single, most intense weather hazard to aircraft Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "For a cumulonimbus cloud or thunderstorm to form the air must have: \
    1.	Sufficient water vapor \
    2.	An unstable lapse rate \
    3.	An initial upward boost (lifting) to start the storm process in motion \
    Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "The key feature of the cumulus stage is an updraft. Precipitation beginning to fall from the cloud base is the signal that a downdraft has developed also and a cell has entered the mature stage. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Weather factors can greatly influence a sUAS performance and safety of flight Reference: AC 107-2" },
{ "correct": "C", 
  "explain": "Advection fog forms when moist air moves over colder ground or water. It is most common along coastal areas, but often develops deep in continental areas. Advection fog deepens as wind speed increases up to about 15 knots. Wind much stronger than 15 knots lifts the fog into a layer of low stratus or stratocumulus. Upslope fog forms as a result of moist, stable air being cooked adiabatically as it moves up sloping terrain. Once upslope wind ceases, the fog dissipates. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "All thunderstorms hazards reach their greatest intensity during the mature stage. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "A squall line is a non-frontal, narrow band of active thunderstorms. The line may be too long to easily detour and too wide and severe to penetrate. It often contains severe steady state thunderstorms and presents the single, most intense weather hazard to aircraft Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Two conditions are necessary for structural icing in flight \
    1.	The aircraft must be flying through visible water such as rain or cloud droplets, and \
    2.	The temperature at the point where the moisture strikes the aircraft must be 0 degrees C (32 degrees F) or colder. \
    Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "If the temperature is above standard the density altitude will be higher than pressure altitude. Reference: FAA-H-8083-25" },
{ "correct": "C", 
  "explain": "Unstable conditions are characterized by cumulus clouds, turbulence, showery precipitations and good visibility. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Dry areas get hotter than moist area. Dry fields or dry ground of any nature are better thermal sources than mist areas. This applies to woods or forests, which are poor sources of thermals because of the large amount of moisture given off by foliage. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Between 2000Z and 2200Z there is a 40% probability (PROB) that is the visibility will drop to 1 SM due to a thunderstorm (TS) and moderate rain (RA)? Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Thermals are updrafts in convective currents dependent on solar heating. A temperature inversion would result in stable air with very little, if any, convective activity. Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Characteristics of a stable air mass include stratiform clouds and fog, continuous precipitation, smooth air, and fair to poor visibility in haze and smoke. Reference: FAA-H-8083-25" },
{ "correct": "B", 
  "explain": "Local condition, geological features, and other anomalies can change the wind direction and speed close to the Earth's surface, making it difficult to control and maneuver the a sUAS. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Advection fog forms when moist air moves over colder ground or water. It is most common along coastal areas. The fog frequently forms offshore as a result of cold water, then is carried inland by the wind. Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Advection fog forms when moist air moves over colder ground or water. It is most common along coastal areas. The fog frequently forms offshore as a result of cold water, then is carried inland by the wind. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Wind shear is an invisible hazard associated with all thunderstorms. Shear turbulence has been encountered 20 miles laterally from a severe storm. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "The key feature of the cumulus stage is an updraft. Precipitation beginning to fall from the cloud base is the signal that a downdraft has developed also and a cell has entered the mature stage. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Standard sea level pressure is 29.92 inches of mercury, standard sea level temperatures is 15 degree C. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "The current conditions at KMDW are 1-1/2 SM visibility (1-1/2 SM) with rain (RA), ceiling overcast at 700 feet (OVC007) Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "You should request a standard briefing any time you are planning a flight and you have not received a previous briefing. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "When air near the surface is warm and moist, suspect instability. Surface heating, cooling aloft, converging or upslope winds, or an invading mass of colder air may lead to instability and cumuliform clouds Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Temperature is one of the most easily recognized discontinuities across a front Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "ASOS is designed to support aviation operations and weather forecast activities. The ASOS will provide continuous minute-by-minute observations and perform the basic observing functions necessary to generate an aviation routine weather report (METAR) and other aviation weather information. Reference: AIM 7-1-11" },
{ "correct": "B", 
  "explain": "A lightning strike can puncture the skin of an aircraft, damage communication and navigation equipment, or hit the remote pilot or crew on the ground. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "A combination of high temperature, high humidity, and high altitude result in a density altitude higher than the pressure altitude which in turn, results in reduced aircraft performance. Reference: FAA-H-8083-25" },
{ "correct": "A", 
  "explain": "Thunderstorms and heavy rain are common, although not always, associated with cold fronts. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Every physical process of weather is accompanied by, or is the result of, unequal heating of the Earth's surface Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Thunderstorm hazards reach their greatest intensity during the mature stage, which is when precipitation begins. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Part 107 require the minimum distance of the sUAS from clouds must be no less than 500 feet below the cloud. The towers depicted 4 NM east of K36 are 292 feet AGL. 292 + 500 = 792 feet AGL. Reference: 14 CFR 107.51" },
{ "correct": "B", 
  "explain": "A squall line is a non-frontal, narrow band of active thunderstorms. The line may be too long to easily detour and too wide and severe to penetrate. It often contains severe steady-state thunderstorms and presents the single, most intense weather hazard to aircraft. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Regardless of the location, crew members must conduct a sUAS Part 107 operations with a minimum visibility, as observed from the location of the control station, no less than 3 statute miles. Reference: 14 CFR 107.51" },
{ "correct": "C", 
  "explain": "A continuous line of thunderstorms, or squall line, may form along or ahead of the front. Squall lines present a serious hazard to pilots as squall type thunderstorms are intense and move quickly. Squalls can occur at any altitude - they are not unique to high- or low-altitude operations. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "Any convective SIGMET implies severe or greater turbulence, severe icing, and low-level wind shear. The forecast may be issued for any of the following; severe thunderstorms due to: \
    1.	Surface winds greater than or equal to 50 knots, or \
    2.	Hail at the surface greater than or equal to 3/4 inch in diameter, or \
    3.	Tornadoes, embedded thunderstorms, lines of thunderstorms. \
    Reference: AC 00-45" },
{ "correct": "C", 
  "explain": "An increase in air temperature or humidity, or a decrease in air pressure (which results in a higher density altitude) will significantly decrease both power output and propeller efficiency. If an air mass is humid, there is more water in it, therefore, less oxygen. Reference: AC 00-6B" },
{ "correct": "A", 
  "explain": "As water vapor condenses or sublimates on condensation nuclei, liquid or ice particles begin to grow. Some condensation nuclei have an affinity for water and can induce condensation or sublimation even when air is almost, but not completely, saturated. Answer (B) is incorrect because the presence of water vapor does not result in clouds, fog, or dew unless condensation occurs. Answer (C) is incorrect because it is possible to have 100% humidity without the occurrence of condensation, which is necessary for clouds, fog, or dew to form. Reference: AC 00-6B”" },
{ "correct": "B", 
  "explain": "The combination of moisture and temperature determine the stability of the air and the resulting weather. Cool, dry air is very stable and resists vertical movement, which leads to good and generally clear weather. Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "Part 107 require the minimum distance of the sUAS from clouds must be no less than 500 feet below the cloud. The towers depicted 8 NM SW of CRP are 1,104 feet MSL. 1,104 + 500 = 1,604 feet MSL. Reference: 14 CFR 107.51”" },
{ "correct": "A", 
  "explain": "When the temperature of the air rises with altitude, a temperature inversion exists. Inversion layers are commonly shallow layers of smooth, stable air close to the ground. The temperature of the air increases with altitude to a certain point, which is the top of the inversion. The air at the top of the layer acts as a lid, keeping weather and pollutants trapped below. If the relative humidity of the air is high, it can contribute to the formation of clouds, fog, haze, or smoke resulting in diminished visibility in the inversion layer. Reference: AC 00-6B”" },
{ "correct": "B", 
  "explain": "The entry RAB35 means that rain began 35 minutes past the hour. Answer (A) is incorrect because mist is reported as BR. Answer (C) is incorrect because there is no format for reporting an altimeter change in a METAR. Reference: AC 00-45" },
{ "correct": "A", 
  "explain": "Wind shear is a sudden, drastic change in wind speed and/or direction over a very small area. Wind shear can subject an aircraft to violent updrafts and downdrafts, as well as abrupt changes to the horizontal movement of the aircraft. While wind shear can occur at any altitude, low-level wind shear is especially hazardous due to the proximity of an aircraft to the ground. Reference: AC 00-6B" },
{ "correct": "B", 
  "explain": "On cool, clear, calm nights, the temperature of the ground and objects on the surface can cause temperatures of the surrounding air to drop below the dew point. When this occurs, the moisture in the air condenses and deposits itself on the ground, buildings, and other objects like cars and aircraft. This moisture is known as dew and sometimes can be seen on grass and other objects in the morning. If the temperature is below freezing, the moisture is deposited in the form of frost. Reference: AC 00-6B" },
{ "correct": "C", 
  "explain": "Part 107 require the minimum distance of the sUAS from clouds must be no less than 500 feet below the cloud. 800 cloud - 500 = 300 feet AGL. Reference: 14 CFR 107.51" },
{ "correct": "A", 
  "explain": "The zone between two different air masses is a frontal zone or front. Across this zone, temperature, humidity and wind often change rapidly over short distances. Reference: AC 00-6B    " },
];